### ISSUE TITLE
Email or Log Exceptions

### ISSUE THREAD

**Issue by DarkAxi0m** [filp/whoops#133]
Just found this and i was thinking It would be nice to have on a production machine, that an Exception handled by
-just showing an Error page (500 or similar) to the user
-then log the exception locally
-or email something like the PrettyPageHandler output to an Email address.

**Comment by avindra** [comment]
Can we reopen this?

Currently in our project we are doing:

```php
$this->whoops->pushHandler(function($exception, $inspector, $run) {
    // Truncated.... we email our error here
    return \Whoops\Handler\Handler::DONE;
});
```

Are there any code samples for hooking into the pretty page handler and:

1) Keeping the original behavior of `PrettyPageHandler`
2) Emailing the output of `PrettyPageHandler` in addition

**Comment by avindra** [comment]
Given that there are many ways to send emails in PHP (in my team's project, we use `PHPMailer`, and I'm sure others are using any number of other methods)....

I think providing some means of hooking into the response from `PrettyPageHandler` so we can email it out as necessary would be ideal.

**Comment by denis-sokolov** [comment]
It’s not an issue, it’s a feature request. Until someone contributes the feature in a PR there’s no value in keeping the issue open. A PR is welcome, albeit for this feature a discussion in advance would be appreciated.

**Comment by avindra** [comment]
@denis-sokolov : Perhaps open this and label it a feature request? Lots of projects follow this pattern as it increases transparency.

I had to do a bit of digging to find this page: https://github.com/filp/whoops/wiki/Possible-features-to-add

**Comment by denis-sokolov** [comment]
It’s a matter of preference. In Whoops not keeping tens of feature request allows us to keep track of actual issues.

**Comment by Julusian** [comment]
For anyone else interested in this, I managed it as follows:
```
use Whoops\Run as Whoops;
use Whoops\Handler\PrettyPageHandler as Handler;

$whoops = new Whoops();
$whoops->allowQuit(false);
$whoops->writeToOutput(false);
$whoops->pushHandler(new Handler());
$body = $whoops->handleException($this->exception);
```
$body contains the html page as a string, so can be emailed or used however you wish

**Comment by reeperbahnause** [comment]
I'm using Slim and I have no idea how to get the PrettyPageHandler body.
I see a few ways like extending the Handler or exchange the middleware but I guess there is an easier way of getting the pretty page. If I would have access to the body emailing it wouldn't be a problem.
Could anyone help me with that?

**Comment by staabm** [comment]
see e.g. https://github.com/redaxo/redaxo/blob/b4da95c603024e660d5686351797e53c96f11a42/redaxo/src/core/lib/error_handler.php#L62-L74 in which we retrieve the contents from the handler as a string.

**Comment by iovino** [comment]
For anyone that wants to use Julusian's approach in a CLI application like I am, you'll need to _set handleUnconditionally_ to true. 

`$handler->handleUnconditionally(true);`
