### ISSUE TITLE
Display arguments of failed function calls

### ISSUE THREAD

**Issue by Anahkiasen** [filp/whoops#15]
Arguments used for each function is stocked in the backtrace, it would be nice if those were displayed somewhere.

**Comment by staabm** [comment]
Maybe we could use symfony/vardumper as a renderer for the parameters

**Comment by canvural** [comment]
@filp, any update on this?

**Comment by denis-sokolov** [comment]
Whoever wants to implement this, consider using #320.

**Comment by denis-sokolov** [comment]
A GitHub issue is a poor medium for a wishlist of features. Moved [to the wiki](https://github.com/filp/whoops/wiki/Possible-features-to-add). Feel free to continue using this issue for a discussion.
