### ISSUE TITLE
PSR-3 Error logging 

### ISSUE THREAD

**Issue by staabm** [filp/whoops#186]
Should we integrate somehow with a PSR3 logger to ease debugging....?

I see places like 
https://github.com/filp/whoops/blob/master/src/Whoops/Handler/PrettyPageHandler.php#L214-L217

which swallows exceptions and therefore might make it sometime really hard to find underlying issues...

I would like to discuss the integration from a whoops-developer point of view.
If we should support error logging from a Application perspective is a different topic.

**Comment by denis-sokolov** [comment]
Does not seem active enough to stay open.
