### ISSUE TITLE
Where to enable for Laravel 5

### ISSUE THREAD

**Issue by mikeerickson** [filp/whoops#240]
Since Whoops has been removed as default error reporter in the soon to be released laravel 5, I am trying to figure out how to make it work.

I have tried various places of activating Whoops, but I cant seem to make it work.   

Have you tried using Whoops with Laravel 5 yet?

**Comment by subdesign** [comment]
Clean article on adding whoops back to L5:
https://mattstauffer.co/blog/bringing-whoops-back-to-laravel-5
