### ISSUE TITLE
Callback handler and fatal errors

### ISSUE THREAD

**Issue by PatrickLouys** [filp/whoops#241]
When I encounter a fatal error and use a callback handler, then the error is shown before the echoed message. On other errors it works fine. 

The PrettyPageHandler does handle the same error correctly.

```
$woops->pushHandler(function($e){
    echo 'Friendly error page';
    return \Whoops\Handler\Handler::DONE;
});
```

Cheers,
Pat

**Comment by denis-sokolov** [comment]
I'm sorry I missed this issue when you have originally posted it.

In PHP one cannot catch fatal errors, and I find that all kinds of different behavior is expected.
If you still experience the problem and want to resolve it, feel free to reopen the issue. But I assume it's outdated now.
