### ISSUE TITLE
Reliance on external URLs

### ISSUE THREAD

**Issue by signet-planet** [filp/whoops#251]
Today I was having laravel pages hang on my development server with the browser status bar showing "waiting for ajax.cdnjs.com...".  Doing a quick grep search your whoops.base.js has an external link to a ZeroClipBoard version 1.3.5 swf file.  The downtime was only temporary but it kept my laravel projects hanging and odd output behaviour until I restarted the chrome browser and cleared the laravel cache completely.  

As this only happened on development sites with the debugging enabled this is not a huge security concern but having an external link does introduce risk to the laravel project so I was wondering if the required zeroclipboard files could be included in your project or better yet added as a dependency (as it is available in composer as zeroclipboard/zeroclipboard) and then the links are always local instead of external.  I also noticed you call the file in version 1.3.5 and the current version of ZeroClipboard is 2.2.0 which may or not have something to do with the unstable file access times today although the fact 1.3.5 came back online I'm assuming it wasn't related to it getting old.

**Comment by staabm** [comment]
Will have a look after holiday

**Comment by KuenzelIT** [comment]
There are two cloudflare usages in layout.html.php:

```html
<script src="//cdnjs.cloudflare.com/ajax/libs/zeroclipboard/1.3.5/ZeroClipboard.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/prettify/r224/prettify.js"></script>
```

I don't like the fact that I am dependent on cloudflare. What do you think about this?

**Comment by staabm** [comment]
Atm we have no mechanics to serve those resources from the server whoops is served from. I think a first step would be to load those scripts asyncronous.

Maybe we can also check if cloudflare is reachable..

**Comment by denis-sokolov** [comment]
@staabm, what do you mean "no mechanics"? What about the same way we handled jQuery in #128?

**Comment by staabm** [comment]
> what do you mean "no mechanics"?

their is no way to load such libs from the server whoops is rendered from using a url (because no front-controller etc). embedding the libs into the page is an option though.

If you want me todo just that, give me a ping.

**Comment by denis-sokolov** [comment]
Yes, I do think that including them into the page the same way we do jQuery is preferable.
If we had that, it'd be good.

**Comment by staabm** [comment]
just had a look at this. It is no problem to "inline" all the required JS files, but the required SWF file is a problem.

The ZeroClipboard.js file has a option to define the path which should point to the ZeroClipboard.swf.
In other words, the ZeroClipboard.js library doesnt allow me to inline the SWF and therefore I will always need a URL (which cannot point to the dev server as pointed out in comments above).

So I think atm we cannot improve this situation.

**Comment by denis-sokolov** [comment]
Good research, thank you.
Well, it seems we're screwed here.

@signet-planet, I'd suggest you to disable plugins by default anyway, it's safer this way and less ads.

**Comment by signet-planet** [comment]
thanks for your work on this.
