### ISSUE TITLE
The "API Documentation" Contains Invalid Syntax

### ISSUE THREAD

**Issue by GrahamCampbell** [filp/whoops#255]
I assume this was intentional to let people know what types to use. It does look strange though.

**Comment by denis-sokolov** [comment]
I don't think it's a problem.
It would be if the code samples would be copy-and-pastable, but these aren't, you still need to replace the parameters to call the functions.
Do you see other risks?

**Comment by GrahamCampbell** [comment]
I think it's silly to provide code samples with invalid syntax.

**Comment by denis-sokolov** [comment]
But they are not code samples, they are more function signatures.
Is the scalar type hints the only problem you see? What about other type hints? Also invalid syntax in the context of calling a function. What about non-static functions displayed as called statically? Assignments to `null` in the parameter list?

**Comment by GrahamCampbell** [comment]
> Is the scalar type hints the only problem you see?

No, you can't type hint when you're actually calling a function...

**Comment by denis-sokolov** [comment]
Did you see the rest of my comment, though? I have, indeed, mentioned the other type hints. Also a laundry list of other problems. Do you want all of them to be fixed or only some?
