### ISSUE TITLE
PlainTextHanlder enhancement. Arguments type

### ISSUE THREAD

**Issue by funivan** [filp/whoops#258]
I propose next enhancement in `PlainTextHandler` 
Add type for `$logger` argument in function `__construct` and `setLogger`

```php
 /**
     * Constructor.
     * @throws InvalidArgumentException     If argument is not null or a LoggerInterface
     * @param  \Psr\Log\LoggerInterface|null $logger
     */
    public function __construct(\Psr\Log\LoggerInterface $logger = null)
    {
       if ($logger) {
         $this->setLogger($logger);
       }
    }

    /**
     * Set the output logger interface.
     * @param  \Psr\Log\LoggerInterface $logger
     */
    public function setLogger(\Psr\Log\LoggerInterface $logger)
    {
        $this->logger = $logger;
    }
```

I can make it and create pull request.

**Comment by denis-sokolov** [comment]
That is a code improvement, but it can possibly break backwards compatibility, thus we can't accept it, sorry. We already clearly state the expected type in the comment section for that method, that's the best we can do at the time, I think.
