### ISSUE TITLE
Silenced errors won't fill error_get_last() array

### ISSUE THREAD

**Issue by mahagr** [filp/whoops#262]
For example the following code (with warnings throwing exception) will not work as the error handler doesn't propagate error to the default handler:

    $success = @mkdir($dir, 0777, true);
    if (!$success) {
        $error = error_get_last();
        throw new RuntimeException("Creating directory '{$dir}' failed on error {$error['message']}");
    }

If directory creation fails, details on why it happened will not be there. To fix this, the error handler should return false on silenced errors.

So in Run::handleError() handler should return false if the error was silenced.

**Comment by staabm** [comment]
@mahagr thanks for the report. Could you provide a testcase and a fix?

**Comment by mahagr** [comment]
Testcase is provided above. I'm just thinking of the fix, but it's not ready yet.

**Comment by mahagr** [comment]
Hmm.. I'm just thinking if we could just return false in the last row without having any checks.

Basically it would cause the function to return false whenever it didn't handle the error, meaning that both silenced and ignored errors get passed forward to the next handler. Because of the default handler will also ignore those errors, it shouldn't have any side effect..?
