### ISSUE TITLE
Dependent on cloudflare

### ISSUE THREAD

**Issue by KuenzelIT** [filp/whoops#264]
There are two cloudflare usages in layout.html.php:

```html
<script src="//cdnjs.cloudflare.com/ajax/libs/zeroclipboard/1.3.5/ZeroClipboard.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/prettify/r224/prettify.js"></script>
```

I don't like the fact that I am dependent on cloudflare. What do you think about this?

**Comment by denis-sokolov** [comment]
Duplicate of #251. Please discuss there.
