### ISSUE TITLE
error-code of \ErrorExceptions not handled properly?

### ISSUE THREAD

**Issue by staabm** [filp/whoops#267]
When using a error to exception "converter" like suggested on php.net [1], the errors'  `$errno` should go into the `severity` property.

Whoops instead uses the `code` property of the ErrorException instead [2].

Should we be able to handle both cases or should this be considered a "convention" whoops brings with it?

[1] http://php.net/ErrorException
[2] https://github.com/filp/whoops/blob/master/src/Whoops/Handler/PrettyPageHandler.php#L130-L134

**Comment by denis-sokolov** [comment]
Good catch, @staabm!

That's really unfortunate that we have a bug like this.
I think we definitely will be setting `severity` to align with PHP.

The `level` though is more complicated.
At the moment the PHP model does not use the `level` property at all.
I do think that removing `level` in our code, as unlikely as it, might break applications that rely on `->getCode()` incorrectly. We shall keep it for the time being (that is, `getCode() === getSeverity()`), and mark a note somewhere that it's deprecated.

**Comment by staabm** [comment]
> The level though is more complicated.

whats the `level` you are referring to?

**Comment by denis-sokolov** [comment]
I meant `code`.

**Comment by staabm** [comment]
ok, will provide a PR then
