### ISSUE TITLE
PrettyPage: Keyboard Navigation

### ISSUE THREAD

**Issue by staabm** [filp/whoops#272]
To enhance the user experince on pretty-pages I would like to propose adding the following keypress handlers:

- Arrow Up/Down to navigate between stack frames (the column on the left, which is ATM only discoverable using the mouse)
- Page Up/Down to scroll the detail panel on the right

Do you miss anything else which might be a good thing to enhance the UX?

Atm you can scroll the frame which has the focus, so either scroll stackframes window (without showing frame details like a click would) or scroll the details window. I don't like using the mouse in between therefore I suggest the above enhancements.

As an alternative we could scroll the stackframes using Arrow Left/Right instead which would preserve browsers default behavior (so you could still scroll the "active window" depending on where you clicked before)

**Comment by denis-sokolov** [comment]
I'd like to minimize the intrusion into default controls. We should focus the main panel on load to allow for regular scrolling.

Then we need to solve the frame navigation. Left and right though is not particularly straightforward.
Perhaps `Ctrl+↑` and `Ctrl+↓`? We can show a tiny hint in the UI (thought less prominent that in my mockup):
![1](https://cloud.githubusercontent.com/assets/113721/6764466/3a831356-cfb9-11e4-8d24-190f05460be9.png)

**Comment by staabm** [comment]
Will provide a PR next week
