### ISSUE TITLE
Whoops screen leaves off trailing '='

### ISSUE THREAD

**Issue by mistakevin** [filp/whoops#276]
The environment variable list leaves off a trailing '=' for a value. For instance `secret+key=` is displayed as `secret+key`. Small thing, but a bug nonetheless.

**Comment by staabm** [comment]
could you send a screenshot so we can see what you mean exactly?

**Comment by mistakevin** [comment]
on the server `OAUTH_CLIENT_SECRET=..............7sW0=`
in whoops:
![screen shot 2015-03-31 at 10 22 37 am](https://cloud.githubusercontent.com/assets/4411115/6922361/2ef4a00c-d790-11e4-88a7-f8ba3aeeb95a.png)

**Comment by staabm** [comment]
both work for me

```php
        $_SERVER['OAUTH_CLIENT_SECRET'] = '..............7sW0=';
        $_ENV['OAUTH_CLIENT_SECRET'] = '..............7sW0=';
```

see http://imgur.com/PNx78WV

**Comment by mistakevin** [comment]
Its a problem (unsolved) with my environment. Not an issue with Whoops. Thanks for the quick replies!
