### ISSUE TITLE
Whoops doesn't catch some errors e.g. missing semicolons in php code

### ISSUE THREAD

**Issue by zacarter** [filp/whoops#278]
Should Whoops display the PrettyPageHandler if the project it is registered under has a php file with a missing semicolon on a line, or similar syntax error like a missing '$' at start of a variable name? I'm not seeing it, and wondering if you would expect it to catch this or not.

**Comment by GrahamCampbell** [comment]
This would result in a php fatal error.

**Comment by staabm** [comment]
a php fatal error can only be handled when whoops-run was registered before.
(thats also a reason why you should register the error handler as soon as possible.

handling of fatal errors is supported see https://github.com/filp/whoops/blob/master/src/Whoops/Run.php#L341-L359

**Comment by denis-sokolov** [comment]
The question is answered very well.
