### ISSUE TITLE
Non Fatal ErrorExceptions

### ISSUE THREAD

**Issue by robinmalburn** [filp/whoops#296]
Whilst trying to implement my own handler today, I ran into a problem when working with non-fatal errors and how they're handled by Whoop\Run.  When the code at [this line](https://github.com/filp/whoops/blob/master/src/Whoops/Run.php#L325) throws the newly created ErrorException, it essentially halts code execution for everything but the exception handler, even if the error raised was a minor warning.  Whilst I can understand this to a degree, it's interesting to note that the [else block](https://github.com/filp/whoops/blob/master/src/Whoops/Run.php#L327) would handle non-fatal errors just fine and allow the code to keep running, allowing the defined handlers to process the error and then using the `allowQuit` configuration to decide whether execution should halt after the error is fully processed.

To try and explain why this is an issue, it's worth noting how I was looking to implement the new handlers:  First of all, one handler was to tie into Bugsnag, allowing me to record any and all errors raised on the system.  Another handler would then be responsible for handling errors when out of debug mode, basically just showing a user friendly "Whoops something went wrong" type of message, without bleeding debug data.  In the Bugsnag handler example, I'd really want to record absolutely all errors so that I can be notified and correct them retrospectively, but for the "end user friendly" handler, we really wouldn't want a simple PHP Notice or Warning to result in the user being kicked to a 500 error screen.  Combining these examples, you can't really use a lower error reporting level, nor the silenced paths feature as it would reduce the effectiveness of the Bugsnag handler.  It also seems like this is something that would be useful even tying in with Whoop's own PlainTextHandler, where simple, non-fatal PHP errors could still be passed to a Logger instance, without needing to bring the system to a stop.

I see two ways of solving the issue: 
1. Always use the implementation in my second link (passing the exception as an argument to a method).
2. Modify the first link's code to check for both `canThrowExceptions` and `allowQuit`.

Option 1 seems like it may be taking a hammer to the problem, so I've got my doubts about that, but it seems like the updated check in option 2 should work fairly well.  That is, of course, unless I'm missing something blindingly obvious as to why that's a bad idea.  If there's no reason not to go with option 2, I'd be happy to submit a patch with the change in place.

**Comment by denis-sokolov** [comment]
Thank you for your extensive description and thoughts.

This seems to be a duplicate of #211.
To summarize: I believe proceeding after a PHP error should be strongly discouraged, it's generally a bad idea. In rare cases where you are responsible of band-aiding a legacy application you can implement that on top of Whoops using `error_reporting` and `set_error_handler`.

I will be closing this now, but feel free to comment if you have additional insights in light of the new information, the discussion may continue.

**Comment by jandreasn** [comment]
@denis-sokolov Here's another vote for adding this behavior as an option. Even though discouraged, an option that's off by default can't hurt? In booboo it's an option so it's something more than a few people find usable: https://github.com/thephpleague/booboo/blob/master/src/Runner.php#L106

Our case: Unforeseen notices and warnings do happen sometimes in production environments, in external libs or new code. We do want these minor errors logged, so that we can fix them. But there's no reason to kill the entire request for the end user just because some developer forgot to check an array index with isset for example.

**Comment by denis-sokolov** [comment]
> But there's no reason to kill the entire request [because of a minor error]

This here is a judgement call and we happen to have varying opinions.
I would be possible open to an option, but in this case you already have this capability using basic PHP, no need to involve Whoops:

```php
$whoops->register();

set_error_handler(function($level, $message, $file, $line){
  if (Whoops\Util\Misc::isLevelFatal($level) {
    retutn;
  }

  logTheWayIWantTo($message, $file, $line);
  return true;
});
```

Yes, this is slightly less convenient than a possible alternative:

```php
$whoops->logAndDoNotThrowMinorErrors(function($message, $file, $line){

});
```

But I do not want to promote continuing execution in a broken state.

**Comment by jandreasn** [comment]
Thanks for taking the time to answer. I do understand your point and yea, there are ways around it. But I still hope that this will be added as a convenient option at some point.
