### ISSUE TITLE
Whoops + Fat-Free

### ISSUE THREAD

**Issue by papa-smurf** [filp/whoops#302]
For some reason, when using Whoops and Fat-Free together, I get the following error when using the PrettyPagehandler:

```
Invalid argument supplied for foreach()
vendor\filp\whoops\src\Whoops\Resources\views\env_details.html.php: 15

15. <?php foreach ($data as $k => $value): ?>
16.     <tr>
17.         <td><?php echo $tpl->escape($k) ?></td>
18.         <td><?php echo $tpl->escape(print_r($value, true)) ?></td>
19.     </tr>
20. <?php endforeach ?>
```

Typecasting the `$data` variable to an array solves this issue for me as `$data` is a string at this point:

`<?php foreach ((array) $data as $k => $value): ?>`

There's probably a perfectly fine explanation for this, but avoiding any additional errors by always typecasting to an array seems like a fair trade off to me.

**Comment by staabm** [comment]
casting a string to an array will omit the warning but the output of the loop shouldn't make sense then?

**Comment by denis-sokolov** [comment]
Are you adding any data tables? Are all of those arrays?

**Comment by papa-smurf** [comment]
I'm not adding anything, I get this error even when using whoops out of the box:

```
$whoops = new Whoops\Run;
$whoops->pushHandler(new Whoops\Handler\PrettyPageHandler);
$whoops->register();

throw new Exception('Computer says no!');
```

It concerns the Environment Variables array, for some reason it's not an array but a string.
Again I've never had this issue before (using no framework or Laravel 4-5) so I'm guessing Fat-Free messes things up and some point.

Doing a datatype check or typecast still seems like a viable improvement to prevent this sort of stuff however.

**Comment by staabm** [comment]
> It concerns the Environment Variables array, for some reason it's not an array but a string.
please check whats in the Environment Variables instead of a array (so print it, maybe it helps to investigate).

**Comment by papa-smurf** [comment]
It's just a string with value 'local'

**Comment by staabm** [comment]
in `$_ENV`?

**Comment by papa-smurf** [comment]
I just confirmed this to be a Fat-Free issue, when setting a Fat-Free variable named ENV (which we use internally for environment recognition), Fat-Free actually overwrites the contents of $_ENV.

This is a terrible approach in more ways than I can count.

**Comment by staabm** [comment]
thanks, please report it to them and x-link the upstream issue here
