### ISSUE TITLE
Undescriptive stacktrace while using PlainTextHandler

### ISSUE THREAD

**Issue by ashish-kataria** [filp/whoops#310]
While using PlainTextHandler for cli we get very undescriptive stacktrace as compared to PrettyPageHandler. So is there any to get full stacktrace in PlainTextHandler also.

**Comment by denis-sokolov** [comment]
Thank you for bringing this to our attention.

Are you sure your codebase does not call `->addTraceToOutput(false)` on the handler anywhere?
Note that PlainTextHandler [is supposed to print out](https://github.com/filp/whoops/blob/master/src/Whoops/Handler/PlainTextHandler.php#L258) the stack trace.

**Comment by denis-sokolov** [comment]
Closing due to a lack of information. Feel free to reopen if you have new information.

**Comment by ashish-kataria** [comment]
On E_ERROR, E_PARSE, E_CORE_ERROR, E_CORE_WARNING, E_COMPILE_ERROR, E_COMPILE_WARNING we are not getting full stacktrace I think its because following error types cannot be handled with a user defined function set_error_handler. Do we have alternative to get full stacktrace in this case?

**Comment by staabm** [comment]
This is something which is not supported by PHP < 7. With PHP7 we also get proper stacktraces for those errors.

**Comment by ashish-kataria** [comment]
But if we don't use our own error handler then we will get proper Call Stack.
