### ISSUE TITLE
Add onlyForAjaxRequests to PlainTextHandler

### ISSUE THREAD

**Issue by ExplodingCabbage** [filp/whoops#319]
The `JsonResponseHandler` offers the `onlyForAjaxRequests` configuration option so that you can get the pretty HTML page when directly navigating to a URL in your browser and a JSON response (which I guess you can parse and display in some sensible way if you're so inclined) in response to XHR requests.

However, if you *don't* want to write any code to parse the JSON response and just want something pretty and readable in the 'Network' tab of your dev tools, the `JsonResponseHandler` sucks; especially if you include the traceback, it becomes almost unreadable. The `PlainTextHandler` would be vastly superior for this use case.

The pretty HTML error responses also aren't ideal if you want to read them in the network tab, since they don't look great in a small window and none of the interactivity works. 

So why not add `onlyForAjaxRequests` to the `PlainTextHandler` and have it behave just like it does on the `JsonResponseHandler`? This would make it usable for people like me who just want a pretty plaintext response to their AJAX calls that they can read in the devtools, but still want to be able to get the cool HTML error pages when navigating to a URL directly.

**Comment by denis-sokolov** [comment]
This makes a lot of sense.

Would you be willing to put your name on Whoops? You can add the feature yourself!
The simplest way is to more or less copy all related logic from [`JsonResponseHandler`](https://github.com/filp/whoops/blob/master/src/Whoops/Handler/JsonResponseHandler.php) to [`PlainTextHandler`](https://github.com/filp/whoops/blob/master/src/Whoops/Handler/PlainTextHandler.php).

Of course, we could also move this out into the [base handler](https://github.com/filp/whoops/blob/master/src/Whoops/Handler/Handler.php) itself.

**Comment by denis-sokolov** [comment]
This will be closed in #321, please follow the topic there.
