### ISSUE TITLE
Release 1.1.8/9 Removes Support for PHPStorm, Released from wrong tag

### ISSUE THREAD

**Issue by loren138** [filp/whoops#336]
1.1.8 and 1.1.9 released as changes from the 1.1.6 release rather than the 1.1.7 release.

Parent for 1.1.8 (https://github.com/filp/whoops/commit/df6f140c89876f687c98c8af4f07ae09cf6bdc2e) is 37b5e65 which is 1.1.6 (https://github.com/filp/whoops/tags)

$editors array in 1.1.8:
https://github.com/filp/whoops/blob/1.1.8/src/Whoops/Handler/PrettyPageHandler.php#L71

$editors array in 1.1.7:
https://github.com/filp/whoops/blob/1.1.7/src/Whoops/Handler/PrettyPageHandler.php#L71

**Comment by denis-sokolov** [comment]
Just how many mistakes could I have made with a single patch release?
Thank you for pointing this out. Released 1.1.10 that is identical to 1.1.7.

**Comment by GrahamCampbell** [comment]
> Released 1.1.10 that is identical to 1.1.7.

:(

**Comment by GrahamCampbell** [comment]
1.1.10 > 1.1.9

**Comment by denis-sokolov** [comment]
What do you mean?

**Comment by denis-sokolov** [comment]
Perhaps I expressed myself unclearly. I have released 1.1.10 that is essentially a revertion to 1.1.7.
Because 1.1.8 and 1.1.9 were broken messes with no positive changes.

**Comment by loren138** [comment]
We did lose: https://github.com/filp/whoops/commit/df6f140c89876f687c98c8af4f07ae09cf6bdc2e
The documentation that it isn't PHP7 compatible.  Not sure if that was important.

**Comment by denis-sokolov** [comment]
Thanks for letting me know. I dropped df6f140 on purpose.
Whoops is partially compatible, and I wanted to revert that specific commit.
I would now like to forget 1.1.8 and 1.1.9 ever happened and continue as if 1.1.10 was 1.1.7 all along. :)
