### ISSUE TITLE
Error in example at https://filp.github.io/whoops/

### ISSUE THREAD

**Issue by ExplodingCabbage** [filp/whoops#342]
Sorry if this is the wrong place to open this; I couldn't find the source of https://filp.github.io/whoops/ anywhere on GitHub.

There's an example at https://filp.github.io/whoops/ that has this in it:

```php
// Add a special handler to deal with AJAX requests with an
// equally-informative JSON response. Since this handler is
// first in the stack, it will be executed before the error
// page handler, and will have a chance to decide if anything
// needs to be done.
$run->pushHandler(new JsonResponseHandler);
```

But nothing in the code actually makes that `JsonResponseHandler` only handle AJAX requests. The comment and code don't match. Unless I'm being thick, there's no version of Whoops for which this would ever have worked as documented.

Since many people will probably blindly copy the example, it'd be good if it could be updated to actually only add the handler for Ajax requests.

**Comment by staabm** [comment]
You can find the source of the website in https://github.com/filp/whoops/tree/gh-pages

**Comment by staabm** [comment]
The code of the website is on https://github.com/filp/whoops/tree/gh-pages

Feel free to PR improvements

**Comment by ExplodingCabbage** [comment]
Done: https://github.com/filp/whoops/pull/343
