### ISSUE TITLE
Refactor Misc* methods into functions.php

### ISSUE THREAD

**Issue by staabm** [filp/whoops#351]
From https://github.com/filp/whoops/blob/master/src/Whoops/Util/Misc.php
To https://github.com/filp/whoops/blob/master/src/Whoops/functions.php

The Misc class only contains static helper methods.. Those could -for consistency - live with the other helper fns directly in the whoops-namespace

**Comment by denis-sokolov** [comment]
Hm. I agree we should fix the inconsistency, but maybe the other way around?
After all, the Misc class existed before and we now have dependencies on it, it would be less disruptive to keep it there.

**Comment by staabm** [comment]
I am fine with either way.

**Comment by GrahamCampbell** [comment]
:-1: for going to functions.php.

**Comment by staabm** [comment]
Personally I think the functions.php is the better approach, but we will take everything into the Util class to keep BC.
