### ISSUE TITLE
PHP 5.5 minimum requirement?

### ISSUE THREAD

**Issue by mahagr** [filp/whoops#356]
Is there a real reason why you bumped minimum PHP requirement to 5.5.9 instead of 5.4.0?

I'm asking this because of I have a project where I'm using whoops and I need to support everything between 5.4 and 7.0. I can eventually raise the PHP minimum, but not without prior notice to the users.

**Comment by vinkla** [comment]
You can use version `1.0` for PHP `5.4`.

**Comment by vinkla** [comment]
We can't keep maintain packages for old and unsupported versions of PHP. Developers should start upgrading their environments.

**Comment by staabm** [comment]
the reasons are documented in the 2 related PRs

https://github.com/filp/whoops/pull/350
https://github.com/filp/whoops/pull/354

**Comment by mahagr** [comment]
I agree on people needing to move forward and updating their servers, but in reality people never do that (and most of them have no idea how to do it) unless they are forced to do it.

With a software that's being used in 10000+ sites with automatic updates, I really cannot just bump the requirements without giving those users a warning long time before it happens.

Unfortunately I've been using master branch because of some important bug fixes (and upcoming PHP 7 support), which means that I need to figure out a way to have the latest features without PHP 5.5 requirement.

Also another question: Why did you make `Run` to be a final class? It was so handy to extend it for my own uses. :)

**Comment by vinkla** [comment]
Using the `master` branch directly is never a good idea. I don't agree we need to warn developers about major releases and you can still use this package 1.0 with older versions of PHP.

**Comment by staabm** [comment]
> With a software that's being used in 10000+ sites with automatic updates, I really cannot just bump the requirements without giving those users a warning long time before it happens.

you can configure composer to provide you a version of whoops, which is sutitable for the current php version

> Also another question: Why did you make Run to be a final class? It was so handy to extend it for my own uses. :)

please speek up in the corresponding PR.

**Comment by denis-sokolov** [comment]
If you have an application that needs to support PHP 5.4 and PHP 7 at the same time, then, it seems, Whoops can not help you, unless you maintain a fork of Whoops that would cherry-pick new features from Whoops 2. I'm sorry, but we have to draw the line somewhere, and drawing it at 5.5 will allow us to move into the brighter future with Whoops 2.

**Comment by mahagr** [comment]
Alright, I was thinking the same; maybe I am just forced to maintain my own fork with PHP 5.4 support for now and later get back to the main version.

My questions have been answered; I was just wondering which PHP 5.4 workarounds you wanted to get rid of, but I think I'll see them when you make more changes.

**Comment by ExplodingCabbage** [comment]
The minimum version bump seems *a little* gratuitous, given that PHP 5.3 remains [the most popular PHP version on the web](http://w3techs.com/technologies/details/pl-php/5/all) and that master is (I think?) currently PHP 5.3-compatible. Wouldn't it have been better to make Whoops 2.0.0 the final 5.3-compatible release with the current feature set, *then* bump the minimum version on master, start replacing old 5.3 constructs with prettier modern ones (e.g. `array()` with `[]`) to make sure the compatibility is truly broken, and then release the next version as 3.0.0?

It's not a huge deal and not worth unpicking now, but that's how I'd recommend handling bumping the minimum PHP version next time a reason to do so comes along. If you've got features sitting on master that don't break compatibility, you might as well get them out in a release *before* you bump the minimum version requirement.

**Comment by GrahamCampbell** [comment]
> The minimum version bump seems a little gratuitous, given that PHP 5.3 remains the most popular PHP version on the web and that master is (I think?) currently PHP 5.3-compatible.

It's not the most popular version among composer users, which is how whoops is intended to be distributed.

**Comment by GrahamCampbell** [comment]
See http://seld.be/notes/php-versions-stats-2015-edition.

**Comment by GrahamCampbell** [comment]
90% of people were using php 5.4+, and 74% were using php 5.5+.

**Comment by ExplodingCabbage** [comment]
Point taken, although I think I stand by my conclusion.

**Comment by GrahamCampbell** [comment]
Respectfully, I disagree with it.

**Comment by denis-sokolov** [comment]
@ExplodingCabbage, the version bump is a _little_ gratuitous indeed. But at some point we need to move forward.

**Comment by vinkla** [comment]
> But at some point we need to move forward.

:+1:

**Comment by franzliedke** [comment]
@denis-sokolov Is this the only major BC break between 1.x and 2.0? I can't find a changelog... ;)

**Comment by denis-sokolov** [comment]
@franzliedke, you’re right, we don’t have a changelog. Shame on us, I don’t know how it happened, I will add the migration guide promptly.

PHP version requirement, but also `Run` is now not extendable by user classes. If you did not inherit from `Run`, you should be fine.

**Comment by prisis** [comment]
@denis-sokolov you can use https://github.com/skywinder/github-changelog-generator to create on :)

**Comment by GrahamCampbell** [comment]
There is zero point in having an autogenerated change log. People can just read the commit history to give the same effect.

**Comment by franzliedke** [comment]
Well, it *is* hard to see which commit belongs to which version on GitHub.

**Comment by ExplodingCabbage** [comment]
@franzliedke https://github.com/filp/whoops/compare/1.1.9...2.0.0 is easy enough to read, although admittedly GitHub makes it obnoxiously difficult to view this compare (you need to construct the /compare URL yourself).

**Comment by ExplodingCabbage** [comment]
(Though, of course, as others have already quite correctly pointed out, a list of commits is not a substitute for a human-optimised changelog and migration guide.)
