### ISSUE TITLE
highlight Current Line

### ISSUE THREAD

**Issue by youssefhad** [filp/whoops#359]
i'm using 2.0.0-alpha2 release and highlighting the error line doesn't work

**Comment by denis-sokolov** [comment]
:(

**Comment by denis-sokolov** [comment]
I'm sorry, in case you thought I was impolitely refusing, I wasn't.
I honestly expressed sadness at the fact that it doesn't work.

Could you please explain why you have closed the issue?

**Comment by youssefhad** [comment]
no it's not your answer :)
i just i'll wait until the official release,

**Comment by youssefhad** [comment]
thanks :+1:
