### ISSUE TITLE
[Laravel 5.2] Causing HttpResponseException on form submit

### ISSUE THREAD

**Issue by cornex** [filp/whoops#361]
Hello, following this tutorial at https://mattstauffer.co/blog/bringing-whoops-back-to-laravel-5 and has always worked, now in laravel 5.2 it seems to just throw me HttpResponseException upon form submit. 

If the form is empty, it works just fine. If it not met the FormRequest rules it seems to throw HttpResponseException.. 

Any ideas? Thanks :)

**Comment by denis-sokolov** [comment]
I don't really know. If you or anyone else figures it out, I would gladly add it to the description.
In the meantime [I have added](https://github.com/filp/whoops/commit/a327942c50cbd62b25c6fbe08f173031ce25fbff) the note to the Readme about this.

**Comment by GrahamCampbell** [comment]
It's working fine in L5.2 using my exceptions package.

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-Exceptions

**Comment by denis-sokolov** [comment]
Hey, this is cool, why did you not about this thing before? 
[I've added it](https://github.com/filp/whoops/commit/d6d1dfaac6dc200516317d842d525b8b70d2c390) to the Readme. @cornex, try it out, hopefully it works even better for you!

**Comment by cornex** [comment]
Thanks a lot @GrahamCampbell , working like a charm :)

**Comment by nicolasbinet** [comment]
I have the same problem with both whoops & laravel-exceptions.
When creating a custom validator, I get the "HttpResponseException no message" error page.
Any idea what could cause that ?
For the rest it works like a charm.
