### ISSUE TITLE
Inline SVG instead of base64 dumped binary images

### ISSUE THREAD

**Issue by staabm** [filp/whoops#367]
Investigate whether we could reduce page weight by replacing the `background: url('data:image/png;base64 ...)` images with inlined svg.

Also check browser compatibility.

**Comment by vinkla** [comment]
Great idea! Browser compatibility should be fine, svgs are [supported in all big browsers](http://caniuse.com/#feat=svg). This will make it look better on all screens.

**Comment by prisis** [comment]
Im too :+1:

**Comment by WesamMikhail** [comment]
Sounds great!

**Comment by prisis** [comment]
I will change it today :)
