### ISSUE TITLE
Consider delegating output and exit to userland

### ISSUE THREAD

**Issue by guiwoda** [filp/whoops#375]
Using Whoops is dead simple, and I love that. But I'm on a scenario where I want to be in charge of how a response is made, when it is sent and specially when execution stops.

I know right now I could be able to do this by skipping `Whoops\Run` and just using the handlers, but would you be open to discuss a different design, where *standalone* usage may deal with sending content and exiting, but *framework* integrations would delegate those things and just return either `Psr7\Reponse`s or strings?

**Comment by denis-sokolov** [comment]
This is possibly quite interesting, but I'm afraid will require another BC breakage in Whoops. :(

**Comment by staabm** [comment]
With the newly added systemfacade this can be easily achieved by passing in a custom instance, can't it?

**Comment by patrickbrouwers** [comment]
This seems to bypass it:

```php
$whoops = new Run();
$whoops->allowQuit(false);
$whoops->writeToOutput(false);
$whoops->pushHandler(new PrettyPageHandler);

$html =  $this->whoops->handleException($e);
```

**Comment by staabm** [comment]
@guiwoda does the above work for you?

**Comment by guiwoda** [comment]
@staabm yep! That'll do!
