### ISSUE TITLE
add list of included files

### ISSUE THREAD

**Issue by pdjshog** [filp/whoops#376]
by php function get_included_files();

**Comment by staabm** [comment]
In which situation do you need this information? Whats sour use case?

**Comment by AdityaSinghChauhan** [comment]
get_included_files() -  Returns an array with the names of included or required files.

<?php 
include 'pqrs.php';
include_once  'pqr.php';
require 'xyz.php';
require_once 'xyzw.php';
$display_inlcuded_files = get_included_files();

foreach ($display_included_files as $display_name) {
    echo $display_name."\t";
}

**Comment by denis-sokolov** [comment]
Thank you @pdjshog for your suggestion. As @staabm has correctly pointed out, it is unclear why you'd need this information. Every feature needs to be useful enough to offset the cost of adding it and the cost of complexity it adds. I find it unlikely that `get_included_files` does, but if you can explain why it would be useful, feel free to comment in this issue.
