### ISSUE TITLE
webkitMovementX / Y is deprecated (Chrome)

### ISSUE THREAD

**Issue by SourceCode** [filp/whoops#382]
While using the 2.0.* version of whoops - this error arrives in the console.  Not a major issue but figured I would file a issue since it is deprecated.

![screen shot 2016-02-09 at 4 01 52 pm](https://cloud.githubusercontent.com/assets/55036/12934852/64322146-cf46-11e5-8d99-4a9215de8baf.png)

You may also already be aware - these items just happen to show in the console each time a whoops screen is served.

**Comment by staabm** [comment]
searching thru the whole codebase (current master) did not find any hit for "movement". are you sure this warning is triggered by whoops?

**Comment by SourceCode** [comment]
Ok I dug into this a bit deeper.  It definitely is caused by the whoops package - however it is more the case that it has to do with the javascript libraries being included, which does not involve whoops.

The way to see this occur is to open your console and change from 1 stack trace to another.  You should see the notification in your console.  

I attached 2 screenshots that show examples
![whoops1](https://cloud.githubusercontent.com/assets/55036/13030182/f6baf918-d255-11e5-8829-1e899d456079.PNG)

![whoops2](https://cloud.githubusercontent.com/assets/55036/13030187/14c20208-d256-11e5-90b2-4188071a7d53.png)

I tried to track these down in the javascript being used but couldn't locate anything.  A further search showed a LOT of tickets open on github for many libraries facing this issue.  Apparently this is part of an automatic inclusion of the events because they still exist.

Check this github issue for video.js as an example:
https://github.com/videojs/video.js/issues/2548

I'm not sure if you want to close this issue and report it to the libraries being included in the whoops project or just disregard until something breaks.

**Comment by denis-sokolov** [comment]
Thank you for your research.

I think we'll keep the warnings until one day we update the js dependency libraries and the warnings are suddenly gone.
