### ISSUE TITLE
Open sublime file

### ISSUE THREAD

**Issue by canfiax** [filp/whoops#383]
When I click the following URL:

    subl://open?url=file:///Users/myname/myproject/myfile.php&line=5

Sublime does not open. If I paste the link inside i.e. Safari then choose "SublimeText" from Applications folder, sublime opens, but no file is shown.

Is there anything I need to do additionally?

**Comment by prisis** [comment]
Which OS are you using?

**Comment by canfiax** [comment]
OSX - latest version of El Capitan

**Comment by denis-sokolov** [comment]
You are probably using Sublime Text 3, which possibly requires [an extra tool](https://github.com/saetia/sublime-url-protocol-mac). Please try it out and report your findings together with a precise Sublime version you use.

**Comment by canfiax** [comment]
Thanks. I downloaded this tool: https://github.com/dhoulb/subl

Works fine.

**Comment by canfiax** [comment]
Using Sublime Text 3 build 3013

**Comment by prisis** [comment]
@denis-sokolov maybe we should add it to the doc?

**Comment by denis-sokolov** [comment]
@canfiax, thank you for your report.
@prisis, absolutely, added in c477d2ff70.

**Comment by youssefhad** [comment]
what about Windows ?

**Comment by denis-sokolov** [comment]
@youssefhad, I don’t know nothing about Windows. If you come up with or find a set of instructions, I will gladly add them to the documentation.

**Comment by canfiax** [comment]
@youssefhad, I don’t know nothing about Windows

😂😂
Could imagine it works out of the box on Windows.
