### ISSUE TITLE
Syntax highlighting wrong when first line of snippet is the end of a block comment

### ISSUE THREAD

**Issue by CodeBrauer** [filp/whoops#385]
![bildschirmfoto 2016-02-15 um 17 44 31](https://cloud.githubusercontent.com/assets/2059754/13054876/4af53c84-d40c-11e5-974e-d36c7f7ce947.png)

Line 22 is the end of a block comment and breaks the highlighting

**Comment by staabm** [comment]
duplicate of https://github.com/filp/whoops/issues/214

**Comment by denis-sokolov** [comment]
Thanks for the report! Thanks for the link, @staabm!

**Comment by filips123** [comment]
@acidjazz @denis-sokolov This still sometimes not work. See #588 and google/code-prettify#553 for details.
