### ISSUE TITLE
Fatal error: Class 'Symfony\Component\VarDumper\Cloner\VarCloner' not found

### ISSUE THREAD

**Issue by kinglozzer** [filp/whoops#406]
```
Fatal error: Class 'Symfony\Component\VarDumper\Cloner\VarCloner' not found in /***/vendor/filp/whoops/src/Whoops/Handler/PrettyPageHandler.php on line 122
```

Appears to have been caused by https://github.com/filp/whoops/pull/404, as 2.1.0 works fine. `symfony/var-dumper` is only in `require-dev` -  so it isn’t installed for packages that require `filp/whoops`.

**Comment by GrahamCampbell** [comment]
Doesn't look like a bug. It's in the suggests list: https://github.com/filp/whoops/blob/master/composer.json#L23.

**Comment by GrahamCampbell** [comment]
That means if you want to use that feature, you need to add that dependency yourself. That's why composer dumps out a list of suggested packages when you run install.

**Comment by kinglozzer** [comment]
So `symfony/var-dumper` is a requirement if you want to use `PrettyPageHandler`? That should be documented somewhere if that’s the case...

**Comment by GrahamCampbell** [comment]
> So symfony/var-dumper is a requirement if you want to use PrettyPageHandler? That should be documented somewhere if that’s the case...

It is documented?

**Comment by denis-sokolov** [comment]
This does, indeed, look like a bug. Anyone up to fix it? @jonasdt?

**Comment by GrahamCampbell** [comment]
> This does, indeed, look like a bug.

How is this a bug? We clearly have included this in the suggested dependencies, and we should not be forcing people to install this. Composer will clearly print to the screen that it's suggested, and it'll even tell you why too.

**Comment by kinglozzer** [comment]
`PrettyPageHandler `, prior to 2.1.1, has never required that package to be installed. So it’s either a bug, or a pretty significant backward compatibility break

**Comment by GrahamCampbell** [comment]
I'd say that much is a bug then. ;)

**Comment by jonasdt** [comment]
`symfony/var-dumper` is indeed a requirement if you want to use `PrettyPageHandler`, this was not the case before #404, [this is the culprit](https://github.com/filp/whoops/pull/404/files#diff-cb7af2a30dcc0c802f01e3dd9c020ef5R11)

**Comment by jonasdt** [comment]
Any reason why this isn't a dependency?

**Comment by denis-sokolov** [comment]
We don’t want the users to require the var-dumper, it’s supposed to be optional. @jonasdt, can you adjust your code to be conditional on the VarDumper existing?

**Comment by kinglozzer** [comment]
> Any reason why this isn't a dependency?

Well it was originally added as a suggested package, with usage of it wrapped in `class_exists()`: https://github.com/filp/whoops/commit/6a1c86bb44db1221cb9c35fc8fe3fed536bc1cf7

Since then it has been added to require-dev, and that particular `class_exists()` check has been removed - https://github.com/filp/whoops/pull/387 & https://github.com/filp/whoops/pull/404

**Comment by jonasdt** [comment]
I'll push a fix today
