### ISSUE TITLE
dump output to twig template for theming

### ISSUE THREAD

**Issue by novia713** [filp/whoops#408]
i would like to theme the final look of the error page with Zurb or Bootstrap
but i find very complex decoupling the output as is
whould be possible to print the error page using a template?
this way would be a lot easier

**Comment by denis-sokolov** [comment]
You can already use `addResourcePath` and [`addCustomCss`](https://github.com/filp/whoops/blob/master/src/Whoops/Handler/PrettyPageHandler.php#L482) on the `PrettyPageHandler` to customize pretty much anything, although it is, indeed, not the most supported use case.
