### ISSUE TITLE
not work in phpstorm

### ISSUE THREAD

**Issue by fotobank** [filp/whoops#409]
Hey. sources do not open the file in phpstorm:

use Exception;
use Illuminate\Http\Response;
use Illuminate\Validation\ValidationException;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Whoops\Handler\PrettyPageHandler;
use Whoops\Run;

at class Handler:
       protected function renderExceptionWithWhoops(Exception $e)
    {
        $whoops = new Run;
        $handler = new PrettyPageHandler();
        $handler->setEditor('phpstorm');
        $whoops->pushHandler($handler);
        return new Response(
            $whoops->handleException($e),
            $e->getStatusCode(),
            $e->getHeaders()
        );
    }

What's my mistake?

**Comment by kavin-90** [comment]
Same here phpstrom does not detect whoops classes

**Comment by Rarst** [comment]
What platform are you on? If I got that right `phpstorm://` protocol only works on Macs.

On Windows I have been using [RemoteCall](https://plugins.jetbrains.com/plugin/6027?pr=) plugin for this for a long time (to configure Whoops for it `handler->addEditor( 'phpstorm', 'http://localhost:8091?message=%file:%line' );`).

**Comment by kavin-90** [comment]
phpstorm 2016.1

**Comment by helhum** [comment]
I can confirm that it works nicely with PhpStorm 2016.1 on OSX 10.11

**Comment by denis-sokolov** [comment]
I’m sorry, this does not seem to be a clearly described issue. Given your description, it is impossible to figure out what went wrong. Perhaps you should first try other avenues of action, such as investigate the problem further, ask for help on support forums. If you have new findings, by all means, feel free to add them here and the issue might be reopened.

**Comment by decadence** [comment]
Same here. Looks like phpstorm:// protocol only works on Mac.
Can we change URL for supporting all platforms?
http://develar.org/idea-rest-api/#api-Platform-file
@denis-sokolov
