### ISSUE TITLE
How can I hide some trace frames?

### ISSUE THREAD

**Issue by neomerx** [filp/whoops#410]
Frames collections seems to have a method for filtering out some frames (e.g. closures and other non app specific ones). It's not clear how it should be configured

```php
$run     = new Run();
$handler = new PrettyPageHandler();

$appName = $config->getForApp(C::KEY_APP_NAME);

$handler->setPageTitle("Whoops! There was a problem with '$appName'.");

// I'd like to instruct handler to filter out some of the 'standard' frames for
// better readability. But how?

$run->pushHandler($handler);

$htmlMessage = $run->handleException($exception);
$response    = new HtmlResponse($htmlMessage, 500);
```

**Comment by denis-sokolov** [comment]
I am not aware of any such functionality in Whoops. It would be pretty simple to add, though, PR is welcome!

**Comment by WilliamStam** [comment]
>  It would be pretty simple to add

using eloquent as my DB handler, and the frames it returns are a mile long. looking to filter out the "vendor" frames.

would this be an option you guys would support?

```
$whoops->addTraceFilterCallable(funtion($frame){
    return true;
})
```

then `vendor/filp/whoops/src/Whoops/Exception/Inspector.php` the method getFrames() would read the function, apply the `array_filter` using the callable, ie `array_filter($this->addTraceFilterCallable,$this->frames)`

**Comment by denis-sokolov** [comment]
@WilliamStam, that looks good. Maybe call it “addFrameFilter”, but we can bikeshed the PR later, of course.

**Comment by WilliamStam** [comment]
@AmraniCh you are awesome! i was revisiting this again and started looking through the code to see if i can implement it.  

for anyone else finding this:

```
 $whoops = new \Whoops\Run;
 $whoops->addFrameFilter(function($item){
        if (!str_contains($item->getFile(), DIRECTORY_SEPARATOR . "vendor" . DIRECTORY_SEPARATOR)){
            return true;
        }
       return false;
 });
  
 $whoops->register();
```

**Comment by AmraniCh** [comment]
@WilliamStam thanks, I believe your code example could be more simplified like this :

```php
$whoops = new \Whoops\Run;
$whoops->addFrameFilter(function($item) {
    return !str_contains($item->getFile(), DIRECTORY_SEPARATOR . "vendor" . DIRECTORY_SEPARATOR);
});
$whoops->register();
```

Or If you're running on PHP versions >= `7.4`, you can use arrow functions :

```php
$whoops = new \Whoops\Run;
$whoops->addFrameFilter(fn($item) => !str_contains($item->getFile(), DIRECTORY_SEPARATOR . "vendor" . DIRECTORY_SEPARATOR));
$whoops->register();
```
