### ISSUE TITLE
Production/Development Mode Set

### ISSUE THREAD

**Issue by sant0ro** [filp/whoops#411]
I want to propose the idea of the ability of Whoops have multiple "status engines". But what that means? Most commons of PHP Content Frameworks, like Yii, uses Advanced Exception System, in the case of Yii, their Exception system is based on Whoops, but edited. The ability of change into Development or Production Mode, is a special configuration that you can "switch" the way of how Whoops will handle the Exceptions. Of course you can create dynamic and custom "switch" key-sets, not only production and development. In these key sets you can change which Page Handler will be invoked (PrettyPageHandler, JsonHandler, etc) and, as example, set if the Stack Trace (Frame Set) will appear or not. The good of the last example is the ability of not showing the Source Code (that is presented and displayed for the end-user) in the Error Page. But only show the Error Code, Error Message and Type. Other functionalities is the Change of Page Title for each "switch key-set".

The Key-Sets are presented by a Interface (KeySetInterface), and they are populated by a Factory (WhoopsKeySetFactory)...

This idea is a draft, but really important on my opinion.

Cheers,

**Comment by denis-sokolov** [comment]
Correct me if I’m wrong, but you can implement this fully on top of Whoops, without any modifications in Whoops, by conditionally creating a different instance of Whoops with different handlers.

**Comment by sant0ro** [comment]
Yes, but is really nice if this implemented in the Whoops Core as a functionality. 

In my opinion.
