### ISSUE TITLE
Laravel Master Form error validation not working

### ISSUE THREAD

**Issue by maki10** [filp/whoops#412]
Like a title say the whoops did'n work well.
``public function store(Item $item, CheckItemsField $request)
{		
$item->create($request->input());
return back();
}
``

`    public function rules()
    {
        return [
            'name' => 'required',
            'slug' => 'required|unique:items,slug',
            'price' => 'required'
        ];
    }
`

**Comment by denis-sokolov** [comment]
I’m sorry, this does not seem to be a clearly described issue with Whoops. Given your description, it is impossible to figure out what went wrong. Perhaps you should first try other avenues of action, such as investigate the problem further, ask for help on support forums. If you have new findings, by all means, feel free to add them here and the issue might be reopened.
