### ISSUE TITLE
Errors in Whoops view.

### ISSUE THREAD

**Issue by Tjoosten** [filp/whoops#416]
Hi i got a macbook 13 inch retina with Safari as browser. But woops gives errors in the view.
<img width="398" alt="schermafbeelding 2016-05-20 om 13 45 12" src="https://cloud.githubusercontent.com/assets/5157609/15426808/439114b6-1e91-11e6-9b22-cc23f690a11c.png">

**Comment by prisis** [comment]
That are some laravel errors and not some from whoops.

Can you tell me what you exactly mean with errors in view?

**Comment by staabm** [comment]
I guess he means that the text overflows to the right.

**Comment by Tjoosten** [comment]
@staabm your right!

**Comment by Ailme** [comment]
Hi. I see in DevTools Console: **Uncaught ReferenceError: Clipboard is not defined**

`var clipboard = new Clipboard('.clipboard');`

**Comment by denis-sokolov** [comment]
I think this has just been fixed in #397. Thanks for reporting!
