### ISSUE TITLE
bug in handleError() method

### ISSUE THREAD

**Issue by Perf** [filp/whoops#418]
Description: when you set Whoops to ignore some error type in some path, yes, it will silence Whoops and ignore it, but it will also silence all the next error handlers.

Example:
```php
function simple_error_handler($errno, $errstr) {
    var_dump($errno, $errstr);
    return false;
}
set_error_handler('simple_error_handler', E_ALL);

trigger_error('simple_error_handler was set up', E_USER_NOTICE);

require_once __DIR__ . '/vendor/autoload.php';
$whoops = new \Whoops\Run;
$whoops->silenceErrorsInPaths('/.*/', E_USER_NOTICE);
$handler = new \Whoops\Handler\PrettyPageHandler;
$whoops->pushHandler($handler);
$whoops->register();

trigger_error('whoops error handler was set up', E_USER_NOTICE);
```
**You will never see 2nd message** `whoops error handler was set up`, because in `Run::handleError()` at line `323` it returns `true` instead of `false`.
```php
if ($pathMatches && $levelMatches) {
    // Ignore the error, abort handling
    return true;
}
```
As you know, returning `true` from error handler breaks execution cascade of error handlers. I think that silencing error globally is not expected behaviour.

Please fix that bug, or maybe make that behaviour at least configureable.
Thank you!

**Comment by denis-sokolov** [comment]
Thank you for your constructive and extensive feedback.

The term “silence” in `silenceErrors` implies the errors will have no effect at all. Changing the behaviour would be confusing. Besides, we do not propagate errors handled by Whoops, so adding `silence` could actually make new effects be added, that is counter-intuitive.

But perhaps that is also not necessary. If you want to add different behaviour to your errors, you can add a `set_error_handler` _after_ `$whoops->register();` and do conditional logic there.
