### ISSUE TITLE
Class 'Symfony\Component\VarDumper\Caster\Caster' not found

### ISSUE THREAD

**Issue by garygreen** [filp/whoops#419]
Tried installing 2.1.2 into a Laravel 5.0.0 project and this is what I get. Shouldn't the `"symfony/var-dumper": "~3.0"` requirement be in `require` rather than `require-dev` ?

**Comment by staabm** [comment]
we intentionally added it to require-dev so the actual project can opt in for this feature or not.

It seems we are missing some kind of `class_exists` to make it a proper feature detect though.

**Comment by GrahamCampbell** [comment]
Yes, this is not a bug, and can be closed.

**Comment by garygreen** [comment]
That's a bit confusing because if whoop depends on it for it to function properly then why isn't it pulled in? If it's optional as part of a certain displayer then it should at LEAST be in the `suggests` to avoid any confusion.

**Comment by staabm** [comment]
it is a bug, because we should not run into a class not found..

**Comment by garygreen** [comment]
It should probably do a class_exists if it's optional, shouldn't be getting class not found on an optional dependency..

**Comment by prisis** [comment]
We have a check for this on https://github.com/filp/whoops/blob/d13505b240a6f580bc75ba591da30299d6cb0eec/src/Whoops/Util/TemplateHelper.php#L84 so this https://github.com/filp/whoops/blob/d13505b240a6f580bc75ba591da30299d6cb0eec/src/Whoops/Util/TemplateHelper.php#L119 should not be called.

**Comment by garygreen** [comment]
I have `VarCloner` but I don't have `Caster` -- I think VarCloner has always been in an older version of vardumper but Caster only in a more recent one (>=2.7).

**Comment by garygreen** [comment]
Imo this should be changed:

```
if (!$this->htmlDumper && class_exists('Symfony\Component\VarDumper\Cloner\VarCloner')) {
```

to

```
if (!$this->htmlDumper && class_exists(Caster::class) {
```
