### ISSUE TITLE
REPL

### ISSUE THREAD

**Issue by schickling** [filp/whoops#42]
I don't know if this is even possible in php but for ruby there exists a Gem (https://github.com/charliesome/better_errors) providing support for a [REPL](http://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop) inside the browser for debugging and runtime information. I never saw something like this in PHP but I think that might be great and a huge improvement to the PHP community.

What do you guys think about this feature request?

**Comment by denis-sokolov** [comment]
A GitHub issue is a poor medium for a wishlist of features. Moved [to the wiki](https://github.com/filp/whoops/wiki/Possible-features-to-add). Feel free to continue using this issue for a discussion.

**Comment by filips123** [comment]
You could collaborate with [PsySH](https://github.com/bobthecow/psysh) and make online REPL for PHP. See #585.
