### ISSUE TITLE
Adding Gitter

### ISSUE THREAD

**Issue by prisis** [filp/whoops#423]
What you think about it, if we add a gitter chat to whoops?

**Comment by denis-sokolov** [comment]
What need (use case) would that solve?

**Comment by prisis** [comment]
If someone has questions about whoops or need help, is much faster to answer as a ticket on github

**Comment by denis-sokolov** [comment]
To have someone answer quickly there must be someone in the chat to answer. I don’t know who would that be. :)

**Comment by prisis** [comment]
Yeah you right about this point :)

**Comment by denis-sokolov** [comment]
Also, I bring your attention to the fairly succesful chat we had in this issue. It also has benefits that it is visible to other people and is searchable in the project issues.
