### ISSUE TITLE
No stack when ErrorException is thrown by Laravel

### ISSUE THREAD

**Issue by jp7carlos** [filp/whoops#424]
Laravel throws ErrorException in some places like errors in views. Whoops threats ErrorException as if they all were being thrown by a shutdown handler:

https://github.com/filp/whoops/blob/master/src/Whoops/Exception/Inspector.php#L168

I think at this point (PHP 7) most errors are catchable with a custom error handler, while others still need a shutdown handler.

Maybe changing the code to something like this would be a good compromise between error handler/shutdown handler:

    if (!$e instanceof \ErrorException || !extension_loaded('xdebug') || !xdebug_is_enabled()) {
            return $traces;
    }

Instead of the current code which returns an empty stack:

    if (!extension_loaded('xdebug') || !xdebug_is_enabled()) {
        return array();
    }

Thx!

**Comment by denis-sokolov** [comment]
But the code at your link looks exactly as you mentioned. It does not look as you claim. Perhaps you had an old version of Whoops? Let us know if you have new information.

**Comment by jp7carlos** [comment]
Thx for your reply. My only problem is that it returns an empty array at this line:
https://github.com/filp/whoops/blob/master/src/Whoops/Exception/Inspector.php#L177

      if (!extension_loaded('xdebug') || !xdebug_is_enabled()) {
          return [];
      }

I don't know what was the initial reasoning for this but I think it's weird for a library that's supposed to make debug easier to show nothing when there's an error, just because someone doesn't have xdebug installed.

Maybe change it to:

      if (!extension_loaded('xdebug') || !xdebug_is_enabled()) {
          return $traces;
      }

**Comment by denis-sokolov** [comment]
The code is, admittedly, a bit confusing.

Note that that `return` statement is only hit when the severity of the error is fatal. Which means we got here from a shutdown handler. In those cases the traces regular PHP provides are useless, as they only go until the shutdown handler, not to the actual error.

Does Laravel throw error exceptions with fatal severity errors? That is confusing.

**Comment by jp7carlos** [comment]
> is only hit when the severity of the error is fatal

    if (!Misc::isLevelFatal($e->getSeverity())) {

It is only hit when the severity is **NOT** fatal.

Thx.

**Comment by denis-sokolov** [comment]
Well, yes, but in that condition we do return the traces:

```php
if (!Misc::isLevelFatal($e->getSeverity())) {
    return $traces;
}
if (!extension_loaded('xdebug') || !xdebug_is_enabled()) {
    return [];
}
```

**Comment by jp7carlos** [comment]
You're right, sorry. That's what happens when you try to reply in the middle of other tasks.
I will try to add more context later today.
