### ISSUE TITLE
Error in code view with amperstand

### ISSUE THREAD

**Issue by tsmgeek** [filp/whoops#425]
Seems amperstands screw up display.
![image](https://cloud.githubusercontent.com/assets/5859988/16685763/33f7a57a-4505-11e6-8f39-3e33148dd152.png)

**Comment by james-radford-854** [comment]
This was happening to me when I had the [Source Code Pro](https://github.com/adobe-fonts/source-code-pro) font installed in Windows. Uninstalling this font resolved the issue for me. I then installed the latest version of the font, which does not appear to suffer from this problem.

**Comment by denis-sokolov** [comment]
I assume the problem is resolved for now.
