### ISSUE TITLE
Monolog & Whoops - Logging errors we don't want to display

### ISSUE THREAD

**Issue by inssein** [filp/whoops#430]
I am currently working on a fairly old codebase and trying to improve it, but I am stuck on figuring out how to make Whoops work with Monolog.

I integrated Whoops a few months ago, and it has been working out fairly well (for dev and prod). But now, I need to integrate Monolog, and I am having a lot of difficulties as I can't find a good way to do this.

From Googling, everyone who wants to integrate whoops with monolog adds monolog as a handler to whoops.  However, I have a few issues with that.

1. I want to log all errors, but only display fatal errors / unhandled exceptions in production
2. The monolog ErrorHandler seems to add better information about the calling function and its parameters.

So what I did was I registered both separately. This is almost there, except I've got another two issues:

1. Whoops is displaying every error that is reported. How can I limit this without changing error_reporting as I want to log all errors?
2.  After monolog logs a PHP error, Whoops handles the same error, converts it to an exception, and then Monolog again catches it.. (causing double logging).

I can't think of a clean way to solve the above issues. Is the solution just to write a separate production error handler and not use whoops in prod (if I want to log everything but not display everything)?

Edit:
The solution might be as simple as disabling error handling in prod.

**Comment by inssein** [comment]
Another question:

Why does Whoops throw the exception, instead of just handling it?

As in, why do this:
```PHP
$exception = new ErrorException($message, /*code*/ $level, /*severity*/ $level, $file, $line);
if ($this->canThrowExceptions) {
    throw $exception;
} else {
    $this->handleException($exception);
}
```
Instead of:
```
$exception = new ErrorException($message, /*code*/ $level, /*severity*/ $level, $file, $line);
$this->handleException($exception);
```

**Comment by denis-sokolov** [comment]
We throw exceptions for consistency, to handle everything in the same way. This also allows catching those exceptions in user code.

I don't know how to help you with the main issue. If you have more concrete ideas how to improve Whoops to allow for your case, let us know. A PR would be even better. Until then, this is hardly actionable. :(
