### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by jokerham** [filp/whoops#433]
I get the following error when running the command below.
What is wrong here?

     composer require --dev flip/whoops

                                                                               
       [InvalidArgumentException]                                                   
       Could not find package flip/whoops at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
                                                                               

     require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

**Comment by hultberg** [comment]
´´´´
...version for your minimum-stability (stable).
´´´´

Could you post your composer.json file?

**Comment by jokerham** [comment]
Do you mean this?

{
    "require": {
        "monolog/monolog": "^1.20",
        "league/route": "^2.0",
        "smarty/smarty": "^3.1",
        "Respect/Validation": "^1.1",
        "nesbot/carbon": "^1.21"
    }
}

**Comment by hultberg** [comment]
Hm.. @jokerham. I started digging into this and observed that this worked as intended. Your issue is because you have a typo in the command. It is: ` composer require --dev filp/whoops` not ` composer require --dev flip/whoops` (difference is the **filp**)

**Comment by jokerham** [comment]
Damn imbarassed..  :(
I was so confirmed that it was Flip like flip over.
Does any one know why it is named filp?

**Comment by staabm** [comment]
filp is the shorthand of the creator.

**Comment by denis-sokolov** [comment]
And my speculation is `filp` is for the name Filipe. :)
