### ISSUE TITLE
Suggestion, add stacktrace in a HTML comment on top of document (PrettyPageHandler)

### ISSUE THREAD

**Issue by tomvlk** [filp/whoops#434]
Sometimes I get the prettty page back while I can only view the HTML source itself. I always find myself scrolling down through all the CSS code to find the stacktrace. Maybe it's an idea to add the stacktrace to a HTML comment on top of the prettypage output.

**Comment by staabm** [comment]
Does the browser send headers so we can identify whether you are using the view-source window?

**Comment by tomvlk** [comment]
It's more that you use the chrome debug network tab and click on for example ajax request that returns Whoops pretty page. You can not switch on the HTML viewer there, and it could not be detected I guess.

But it would be possible to include the stacktrace in a comment.

**Comment by staabm** [comment]
having it in a human readable form inside a comment sounds like a good idea

**Comment by dequis** [comment]
Prior art: the werkzeug debugger puts the traceback [at the end of the html][1], which is useful when you end up with an html error spewed in the terminal.

[1]: 
https://github.com/pallets/werkzeug/blob/5a2bf35441006d832ab1ed5a31963cbc366c99ac/werkzeug/debug/tbtools.py#L117-L123
