### ISSUE TITLE
HttpResponseException reported when in $dontReport

### ISSUE THREAD

**Issue by velvetz7** [filp/whoops#441]
This exception is thrown when a form validation fails, and even though I added this exact exception into the $dontReport list whoops still reports it.

Any idea why this happens?

A possible workaround: 
```
    public function render($request, Exception $e)
    {
        if(!($e instanceof HttpResponseException))
        {
            if (config('app.debug')) {
                $whoops = new Run;
                $whoops->pushHandler(new PrettyPageHandler());

                return new Response(
                    $whoops->handleException($e)
                );
            } else {
                if ($e instanceof ModelNotFoundException)
                    $e = new NotFoundHttpException($e->getMessage(), $e);
            }
        }

        return parent::render($request, $e);
    }
```

**Comment by denis-sokolov** [comment]
I’m sorry, this does not seem to be a clearly described issue. Given your description, it might not even be about Whoops. Perhaps you should first try other avenues of action, such as investigate the problem further, ask for help on support forums. If you have new findings, by all means, feel free to add them here and the issue might be reopened.
