### ISSUE TITLE
[L 5.3] Possibly breaks gracious error handling in App\Exceptions\Handler@unauthenticated()

### ISSUE THREAD

**Issue by YavorK** [filp/whoops#447]
I was trying to implement custom guard and a provider for laravel authentication. I kept hitting an exception page with "**Unauthenticated.**" error message. 

Turns out Laravel 5.3 graciously (throws and) handles Exceptions on unathenticated users. Whoops seems to stop on the exception instead of handling it graciously like L. does. This lost me a good few hours. Removing Whoops and reverting App\Exceptions\Handler.php to it's defaults fixed it.

Possibly check if it works with the standard drivers in L5.3. I am sorry I have not the time to report any further details.

**Comment by denis-sokolov** [comment]
I do not know what you are talking about. In particular, Whoops only handles uncaught exceptions, and I have no idea what do you mean by graciously. By all means, if you have more details at some point, do share and we’ll see what we can do.
