### ISSUE TITLE
(Question) about HandlerInterface

### ISSUE THREAD

**Issue by AyrtonRicardo** [filp/whoops#448]
Hi guys,

Why that Interface depends on class(Run) instead of an Interface(RunInterface)?
```php
interface HandlerInterface
{

/** ... */
    /**
     * @param  Run  $run
     * @return void
     */
    public function setRun(Run $run);
/** ... */

}
```
I saw #391.
It's an error this dependency?

**Comment by denis-sokolov** [comment]
This is indeed an error. I think changing this should be backwards compatible. Want to provide a PR for attribution?

**Comment by AyrtonRicardo** [comment]
@denis-sokolov sure. I'll do this right now!

**Comment by AyrtonRicardo** [comment]
It already exists on master, but doesn't exists a release with it.

I'll wait for it then. 
So, thanks for your time @denis-sokolov  :smile:

**Comment by denis-sokolov** [comment]
Oops, sorry!
