### ISSUE TITLE
Does not work in MAMP with vendor outside of public

### ISSUE THREAD

**Issue by sinkaszab** [filp/whoops#453]
`macOS 10.12 / MAMP PRO 4.0.4 (4107) / PHP 7.0.10`
- Composer loads the class (with a var_dump I can easily see an object has been initialized).
- Whatever I setup on the MAMP GUI Whoops won't show up when I throw an error.
- Uncaught errors just will be logged to screen as per default.

I copied the example project. It threw a Fatal Error:

`PHP Fatal error:  Cannot declare class Exception, because the name is already in use in`

I deleted the class definition. It didn't work just echoed the "Something broke" to my browser's screen.

Sorry to bother you, but I don't have any idea where to start debugging.

**Comment by staabm** [comment]
how did you register whoops?

**Comment by sinkaszab** [comment]
via composer

`composer require filp/whoops`

Files are there in the vendor folder.

composer.json

`"filp/whoops": "^2.1",`

**Comment by staabm** [comment]
this is how you downloaded the library.

see https://github.com/filp/whoops#installing for how to register the handler (step 2 of the installation instructions)

**Comment by sinkaszab** [comment]
Err... Thanks.

__It does not work.__

**Comment by sinkaszab** [comment]
I deleted `Exception extends BaseException { ...` after it threw an error.
First I just registered a basic handle as in the 2nd step. It didn't work, so I tried it with the example file.

**Comment by sinkaszab** [comment]
I have a suspicion that redirection header cannot be executed.

If I drop the `Whoops\Run` object into `var_dump` it will set me out with the following: `Cannot modify header information - headers already sent...`

- That makes me think Whoops will try to send out the header to start the PrettyPagehandler,
- But somehow the borwser won't accept the redirection header,
- or will not get out of the server.
- However, I cannot think of anything right now how to catch that header to examine what could be the problem...

```
$whoops = new \Whoops\Run;
$whoops->pushHandler(new \Whoops\Handler\PrettyPageHandler);
$whoops->register();

var_dump($whoops);
```

```
object(Whoops\Run)[3]
  private 'isRegistered' => boolean true
  private 'allowQuit' => boolean true
  private 'sendOutput' => boolean true
  private 'sendHttpCode' => int 500
  private 'handlerStack' => 
    array (size=1)
      0 => 
        object(Whoops\Handler\PrettyPageHandler)[4]
          private 'searchPaths' => 
            array (size=1)
              ...
          private 'resourceCache' => 
            array (size=0)
              ...
          private 'customCss' => null
          private 'extraTables' => 
            array (size=0)
              ...
          private 'handleUnconditionally' => boolean false
          private 'pageTitle' => string 'Whoops! There was an error.' (length=27)
          protected 'editor' => null
          protected 'editors' => 
            array (size=6)
              ...
          private 'run' (Whoops\Handler\Handler) => null
          private 'inspector' (Whoops\Handler\Handler) => null
          private 'exception' (Whoops\Handler\Handler) => null
  private 'silencedPatterns' => 
    array (size=0)
      empty
  private 'system' => 
    object(Whoops\Util\SystemFacade)[2]
  private 'canThrowExceptions' => boolean true
Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/[edited out]/[edited out].php:[edited out: line no.])
```

**Comment by staabm** [comment]
Are you sure that you sorrounding code doesnt already send the headers?

**Comment by sinkaszab** [comment]
Can make it pretty sure, but still doesn't work.

```
ob_start();
/**
 * @section COMPOSER :: AUTOLOAD
 * -----------------------------
 */

$loader = require __DIR__ . '/vendor/autoload.php';
$loader->add('[my_classes]\\', __DIR__);


/**
 * @section Whoops Pretty Error Handling
 * -------------------------------------
 */

$whoops = new \Whoops\Run;
$whoops->pushHandler(new \Whoops\Handler\PrettyPageHandler);
$whoops->register();

throw new Exception("Error Processing Request", 1);
ob_flush();
```

**Comment by staabm** [comment]
why do you use output buffering?

**Comment by sinkaszab** [comment]
Just exemplary reason.

**Comment by staabm** [comment]
please use a very reduced script just including whoops, register it and throw the exception. does it work then?

**Comment by denis-sokolov** [comment]
I’m sorry, this does not seem to be a clearly described issue. Given your description, it is impossible to figure out what went wrong. Perhaps you should first try other avenues of action, such as investigate the problem further, ask for help on support forums. If you have new findings, by all means, feel free to add them here and the issue might be reopened.

**Comment by sinkaszab** [comment]
# Project buildup
```
|- project root
          |---- vendor // composer
          |---- bootstrap.php
          |---- www
                 |---- index.php
```

## Old case -> Whoops PrettyP.Handler doesn't start.

- index.php is the only file in my public folder that's available from the web. All other files are one stack above. I think as a best practise nothing else should be called from index.php, but the bootstrap file.
- So bootstrap included the composer autoload and then I would also call Whoops. This way Whoops PrettyPageHandler didn't start. Although all Whoops classes seemed to have been instantiated.
- All other dependencies handled by composer worked, e.g. Monolog Logger, SwiftMailer, etc.

## New case -> Whoops PrettyP.Handler does start.

- I include the composer autoload file in the index.php.
- I call Whoops also from index.php => This way it will start...
- However this seems to be a not that good practise...

**Comment by denis-sokolov** [comment]
Ah, fantastic! Now the issue is very well described. Hopefully someone can reproduce and fix this problem. Thank you for clarifying the issue!

**Comment by sinkaszab** [comment]
Sorry, seems, unfortunately this thread just is part of my debugging process...

More and more I have the suspicion that this problem is somehow connected to MAMP. I recently had some issues with file ownerships, read-write privileges. Seems like moving files out of the scope of the `MAMP/htdocs/` folder is just not a good idea. (Try moving it to your Documents folder and you can't write a file. I tried moving error logs away, they couldn't also be written.)

To the bigger truth also relates that I built up my local hosting much like a virtual hosting service.

```
|--MAMP
     |--htdocs // This is localhost -> keeping it for experiments
           |-- index.php
           |-- project_folder // git repo
                  |-- vendor // composer
                  |-- bootstrap.php
                  |-- project.www // this is my visible folder for the projects virtual domain (ssl)
                           |-- index.php
```

However all other composer dependencies yet work fine, maybe the problem lays there that including Whoops in one domain scope and using it in another might cause some issues--including it in the bootstrap php which is http://localhost and using it in https://project.local withing the index.php--when PHP handles errors. In the end all imported php files should be in the scope of the main file where they have been included. (At least in my knowledge.)

**Comment by denis-sokolov** [comment]
Thanks for keeping to inform us of your situation. Of course, it’d be great if Whoops was useful in any situation and not break because of a peculiar vhost setup. However, I am unhappy that it’ll take some effort to reproduce your problem setup. This will cause friction for people fixing Whoops. However, were you to find a workaround or a solution, I’d me more than happy to integrate it into Whoops. In other words, keep us informed!

**Comment by Global-Open-Source** [comment]
what have this with **Mamp** todo ?
