### ISSUE TITLE
Question: how to always show full exception message?

### ISSUE THREAD

**Issue by freekmurze** [filp/whoops#454]
Hi,

thank you for creating this nice package. I love it and use it on every project.

Is there an option to always show the full exception message? More often than not message is longer than the black box on the top left hand.

Example:
![screen shot 2016-10-04 at 09 13 51](https://cloud.githubusercontent.com/assets/483853/19065273/e92b6452-8a12-11e6-9aa0-4c86b720bc4c.png)

**Comment by prisis** [comment]
We added something like this http://g.recordit.co/E0LizFc2T3.gif in #358

**Comment by freekmurze** [comment]
Yea, but I'd like it to be fully open by default. As it stands, I always have to hover over it to see the full message.

**Comment by denis-sokolov** [comment]
The current design direction seems to consider long exception messages rather an exception than a rule. Because of that, unfortunately, your use case is not covered. :(

**Comment by freekmurze** [comment]
Ok, I understand, but I don't agree that most exception message are and should be short

A good exception message states the problem, the data and a possible solution. Good exception messages are mostly longer than what your current design allows for.

**Comment by staabm** [comment]
@freekmurze feel free to provide a PR which shows a alternative design with more space for a message ;)

**Comment by JayBizzle** [comment]
It was much better in one of the older versions where the exception was at the top of the right pane.

**Comment by staabm** [comment]
if you like the old design just stick to whoops 1.*
