### ISSUE TITLE
Indent missing

### ISSUE THREAD

**Issue by undercloud** [filp/whoops#460]
![bug](https://pp.vk.me/c604421/v604421524/52f28/qnfxJZ424Hk.jpg)

Lines 11,12,16 has not indent tabs
Space char code is 9 
5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36

**Comment by denis-sokolov** [comment]
I am sorry, I can not reproduce this. A line with leadings tabs is indented visually fine for me, thanks to the existence of `white-space: pre-wrap` rule.

Are you using the latest Whoops, 2.1.4?

**Comment by staabm** [comment]
which linebreaks does your file use? \n or \r\n ?

**Comment by undercloud** [comment]
Unix in SublimeText

**Comment by undercloud** [comment]
Ideally, we should use space characters instead of tabs. But not everyone follows these rules, a minor error, solution - replacing symbols
