### ISSUE TITLE
Support xdebug-link-clicking

### ISSUE THREAD

**Issue by amenk** [filp/whoops#461]
In Xdebug you can configure clickable file links:

     xdebug.file_link_format="javascript:var rq = new XMLHttpRequest(); rq.open(\"GET\", \"//localhost:8091?message=%f:%l\", true); rq.send(null);"

Can you parse this option and make the file links clickable? Laravel standard exception handler does the same.

**Comment by gharlan** [comment]
Just call [this method](https://github.com/filp/whoops/blob/master/src/Whoops/Handler/PrettyPageHandler.php#L366) with argument "xdebug".
