### ISSUE TITLE
PHP 7.1 Whoops fails to catch fatal error when someting is returned in void function

### ISSUE THREAD

**Issue by alexlvcom** [filp/whoops#465]
Whoops doesn't catch PHP 7.1 Fatal error when something was retunred in void function.
I can see message from error log:
`PHP Fatal error:  A void function must not return a value in /user/www/index.php on line 5`

**Comment by sagikazarmark** [comment]
That's not something that can be fixed, as it is a compile error, and those cannot be handled by a user defined error handler:

> The following error types cannot be handled with a user defined function: E_ERROR, E_PARSE, E_CORE_ERROR, E_CORE_WARNING, E_COMPILE_ERROR, E_COMPILE_WARNING, and most of E_STRICT raised in the file where set_error_handler() is called.

**Comment by denis-sokolov** [comment]
Thank you, @sagikazarmark, for providing this summary!
