### ISSUE TITLE
How to check for fatals explicitly?

### ISSUE THREAD

**Issue by stephan-v** [filp/whoops#467]
Hi,

I am currently wondering how I can check to see which type of error is thrown in my pushHandler. Currently I would like to send an e-mail when a fatal error has been thrown.

I see there is ```isLevelFatal``` helper in ```Misc.php``` in the Utils namespace but I still need to get the last error and check it with that method in my pushHandler.

```$this->system->getLastError()``` seems to be used within Whoops itself but this is calling a private property.

It seems that fatal error go through the handleError message and come out as a generic \ErrorException. This leaves me wondering how to check for a fatal.

**Another question**

It is possible to set a name or some kind of identifier for a custom handler?

What is the best way to go about doing this? Hopefully it is ok to ask here. 

Cheers.

**Comment by denis-sokolov** [comment]
You’re looking for [`getSeverity`](http://php.net/manual/en/errorexception.getseverity.php).

**Comment by stephan-v** [comment]
Am I correct to use that since ```handleError``` converts generic PHP errors to \ErrorException and this only gets called when:

```php
if ($error && Misc::isLevelFatal($error['type'])) {
```

This method will always be the result of a fatal exception?

It also only gets called only once, that is in ```handleShutdown()``` and nowhere else is an \ErrorException thrown. If this is the case I would only haveto check for an \ErrorException to know if I am dealing with a fatal.

Thanks for taking your time so far. If you could confirm this I would be very thankful!

Cheers.

**Comment by denis-sokolov** [comment]
I am not sure how this is relevant for your code. This is an implementation detail for Whoops, is subject to change at any moment without any warning. I don’t understand what you are searching for.

**Comment by stephan-v** [comment]
A way to differentiate between fatals and exceptions.

**Comment by denis-sokolov** [comment]
Once you have an `ErrorException`, you call its [`getSeverity()`](http://php.net/manual/en/errorexception.getseverity.php) and you get a constant from the list of [predefined PHP error constants](http://php.net/manual/en/errorfunc.constants.php). You are then welcome to do whatever behavior based on whatever type of error it is. You can even use our `Misc::isLevelFatal` function to not list all constants yourself.
