### ISSUE TITLE
Broken header sending

### ISSUE THREAD

**Issue by GrahamCampbell** [filp/whoops#469]
The pretty page handler is screwing with the headers, even when `writeToOutput(false);` is called. This is because of https://github.com/filp/whoops/commit/d7d89b0cce35b7dff10aae14d5b075c3c6acd610. That commit should be reverted because it doesn't work, and screws with the global state without being asked.

**Comment by staabm** [comment]
There are more handlers then the prettyPage handler which do this very same step. Should we check the writeToOutput() flag in those sports?

**Comment by GrahamCampbell** [comment]
I have a fix coming very soon...

**Comment by GrahamCampbell** [comment]
There are some other issues that will become apparent with my PR too, when we have more than one handler, we get two of the same header, or more, sent, which screws up some servers, as well as being incorrect.

**Comment by GrahamCampbell** [comment]
@staabm Here we go: https://github.com/filp/whoops/pull/470.

**Comment by staabm** [comment]
> when we have more than one handler, we get two of the same header, or more, sent, which screws up some servers, as well as being incorrect.

Could you elaborate? Can several handlers be invoked for rendering a response for 1 request?

**Comment by GrahamCampbell** [comment]
> Could you elaborate? Can several handlers be invoked for rendering a response for 1 request?

Yes, the while loop continues until a handler says "quit".

**Comment by GrahamCampbell** [comment]
Meh, not a while loop, for loop.

**Comment by staabm** [comment]
Yeah, but the new impl in your PR will send the headers only once, right? So this problem is gone?

**Comment by GrahamCampbell** [comment]
Yes. My PR fixes all the problems I can see with the headers.

**Comment by denis-sokolov** [comment]
Closed in #470.
