### ISSUE TITLE
Type error: Exception expected, instance of ParseError given

### ISSUE THREAD

**Issue by nickpoulos** [filp/whoops#476]
Type error: Argument 1 passed to Whoops\Exception\Inspector::__construct() must be an instance of Exception, instance of ParseError given, called in /home/vagrant/Reporter/vendor/filp/whoops/src/Whoops/Exception/Inspector.php on line 80

I went and dumped out $previousException on line 80, just to see what was going on exactly, and it seems like it's a regular old parse error I made that should have been caught correctly.  Any ideas? 

ParseError {#517 ▼
  #message: "syntax error, unexpected '"formula_whole"' (T_CONSTANT_ENCAPSED_STRING), expecting ']'"
  #code: 0
  #file: "/home/vagrant/Reporter/app/Services/Dashboards/Dashboard.php"
  #line: 228
  -trace: {▼
    50. Composer\Autoload\includeFile() ==> new ParseError(): {▶}
    49. Composer\Autoload\ClassLoader->loadClass() ==> Composer\Autoload\includeFile(): {▶}
    48. spl_autoload_call() ==> Composer\Autoload\ClassLoader->loadClass(): {▶}
    47. include() ==> spl_autoload_call(): {▶}
    46. Composer\Autoload\includeFile() ==> include(): {▶}
    45. Composer\Autoload\ClassLoader->loadClass() ==> Composer\Autoload\includeFile(): {▶}
    44. spl_autoload_call() ==> Composer\Autoload\ClassLoader->loadClass(): {▶}
    43. ReflectionParameter->getClass() ==> spl_autoload_call(): {▶}
    42. Illuminate\Routing\Route->Illuminate\Routing\{closure}() ==> ReflectionParameter->getClass(): {▶}
    41. array_filter() ==> Illuminate\Routing\Route->Illuminate\Routing\{closure}(): {▶}
    40. Illuminate\Routing\Route->signatureParameters() ==> array_filter(): {▶}
    39. Illuminate\Routing\Router->substituteImplicitBindings() ==> Illuminate\Routing\Route->signatureParameters(): {▶}
    38. Illuminate\Routing\Middleware\SubstituteBindings->handle() ==> Illuminate\Routing\Router->substituteImplicitBindings(): {▶}
    37. Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() ==> Illuminate\Routing\Middleware\SubstituteBindings->handle(): {▶}
    36. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() ==> Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(): {▶}
    35. Illuminate\Auth\Middleware\Authenticate->handle() ==> Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(): {▶}
    34. Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() ==> Illuminate\Auth\Middleware\Authenticate->handle(): {▶}
    33. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() ==> Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(): {▶}
    32. Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle() ==> Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(): {▶}
    31. LittleThings\Http\Middleware\VerifyCsrfToken->handle() ==> Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(): {▶}
    30. Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() ==> LittleThings\Http\Middleware\VerifyCsrfToken->handle(): {▶}
    29. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() ==> Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(): {▶}
    28. Illuminate\View\Middleware\ShareErrorsFromSession->handle() ==> Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(): {▶}
    27. Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() ==> Illuminate\View\Middleware\ShareErrorsFromSession->handle(): {▶}
    26. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() ==> Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(): {▶}
    25. Illuminate\Session\Middleware\StartSession->handle() ==> Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(): {▶}
    24. Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() ==> Illuminate\Session\Middleware\StartSession->handle(): {▶}
    23. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() ==> Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(): {▶}
    22. Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle() ==> Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(): {▶}
    21. Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() ==> Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(): {▶}
    20. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() ==> Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(): {▶}
    19. Illuminate\Cookie\Middleware\EncryptCookies->handle() ==> Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(): {▶}
    18. Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() ==> Illuminate\Cookie\Middleware\EncryptCookies->handle(): {▶}
    17. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() ==> Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(): {▶}
    16. Illuminate\Pipeline\Pipeline->then() ==> Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(): {▶}
    15. Illuminate\Routing\Router->runRouteWithinStack() ==> Illuminate\Pipeline\Pipeline->then(): {▶}
    14. Illuminate\Routing\Router->dispatchToRoute() ==> Illuminate\Routing\Router->runRouteWithinStack(): {▶}
    13. Illuminate\Routing\Router->dispatch() ==> Illuminate\Routing\Router->dispatchToRoute(): {▶}
    12. Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}() ==> Illuminate\Routing\Router->dispatch(): {▶}
    11. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() ==> Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(): {▶}
    10. Barryvdh\Debugbar\Middleware\Debugbar->handle() ==> Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(): {▶}
    9. Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() ==> Barryvdh\Debugbar\Middleware\Debugbar->handle(): {▶}
    8. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() ==> Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(): {▶}
    7. Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle() ==> Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(): {▶}
    6. Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() ==> Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(): {▶}
    5. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() ==> Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(): {▶}
    4. Illuminate\Pipeline\Pipeline->then() ==> Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(): {▶}
    3. Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() ==> Illuminate\Pipeline\Pipeline->then(): {▶}
    2. Illuminate\Foundation\Http\Kernel->handle() ==> Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(): {▶}
    1. {main} ==> Illuminate\Foundation\Http\Kernel->handle(): {▶}
  }
}

**Comment by staabm** [comment]
For php7 you should update to whoops 2.x

**Comment by denis-sokolov** [comment]
Indeed, Whoops 1 does not work on PHP 7. Please upgrade to Whoops 2, [the changes](https://github.com/filp/whoops/blob/master/CHANGELOG.md#200) are minor.

**Comment by nickpoulos** [comment]
Ah ok, I did not realize. My mistake!
