### ISSUE TITLE
Add support for Airbrake

### ISSUE THREAD

**Issue by sagikazarmark** [filp/whoops#478]
Recently I created a simple nofw application and I used both Whoops and Airbrake (Errbit actually). Would be nice if Whoops had a handler of it OOTB, or at least separately in a package, but supported officially.

[Here](https://github.com/webplates/nofw/blob/master/src/Infrastructure/Whoops/AirbrakeHandler.php) what I've done, I would be happy to open a PR if you like the idea.

**Comment by denis-sokolov** [comment]
Thank you for providing this code. I think the integration with Airbrake is simple enough that there is no reason for it to be built-in into Whoops. I appreciate your suggestion nevertheless!

**Comment by sagikazarmark** [comment]
Okay, no problem. I placed it in a package: https://github.com/sagikazarmark/whoops-extra
