### ISSUE TITLE
Missing Interface Psr\Log\LoggerInterface

### ISSUE THREAD

**Issue by tflori** [filp/whoops#483]
In `PlainTextHandler` you expect an instance of `Psr\Log\LoggerInterface` - may be you have a dependency that is missing in composer.json?

I changed some dependencies in my app (removed phpdocumentor) and suddenly get this error. I solved by require psr/log but you should fix it on your site.

**Comment by denis-sokolov** [comment]
Thanks! 2.1.7 out with the fix.
