### ISSUE TITLE
show ajax error

### ISSUE THREAD

**Issue by karnash** [filp/whoops#487]
hi there great job.
But now i have a question. i revecive the json error but i could show the json response like a error im using whoops 2 and Laravel 5.2
i wanna show this 
![image](https://cloud.githubusercontent.com/assets/5040782/24072285/754280ae-0bbb-11e7-84f4-d689a83388b7.png)

like this 
![image](https://cloud.githubusercontent.com/assets/5040782/24072306/cb949e88-0bbb-11e7-81e7-d791ab83620c.png)

someone can help. thk a lot

**Comment by staabm** [comment]
for ajax request errors whoops does not provide pre-rendered error pages out of the box. you need to render those based on the provided data in the ajax request on your own.

**Comment by denis-sokolov** [comment]
There is no such functionality in Whoops. It is not a very trivial addition, so you should not expect it to be added any time soon.
