### ISSUE TITLE
Big issue on last commit 7th March [f2950be7da8b8d6c4e77821b6c9d486e36cdc4f3]

### ISSUE THREAD

**Issue by irzhywau** [filp/whoops#491]
Got this error instead of rendered html as it should

Warning: Uncaught exception 'Whoops\Exception\ErrorException' with message 'require(): Filename cannot be empty' in ...../vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php:249

PHP 5.6.10

**Comment by staabm** [comment]
please check with `debug_print_backtrace()` who is calling this function with the "wrong" parameters?

**Comment by denis-sokolov** [comment]
I’m sorry, this does not seem to be a clearly described issue. Given your description, it is impossible to figure out what went wrong. Perhaps you should first try other avenues of action, such as investigate the problem further, ask for help on support forums. If you have new findings, by all means, feel free to add them here and the issue might be reopened.
