### ISSUE TITLE
No support for previous exception?

### ISSUE THREAD

**Issue by terion-name** [filp/whoops#493]
Exceptions are chainable. You catch an exception, throw another and set original as previous.

Sort of:
```
try {
///
} catch(SomeLibraryInternalException $e) {
 throw new SomeParentProcessFailedException('your process failed because of something', 0, $e);
}
```

As I see, previous exceptions are not listed on whoops page. This is configurable, or there is no support for that? If no support, can it be added?

**Comment by denis-sokolov** [comment]
I’m pretty sure we already show the entire traceback including the previous exceptions, and their exception messages. [Relevant piece in the code](https://github.com/filp/whoops/blob/4bbb334b3a3152827b3767d333f907f6834e7c5e/src/Whoops/Exception/Inspector.php#L147).
