### ISSUE TITLE
not installing on laravel 5.4

### ISSUE THREAD

**Issue by brazitech** [filp/whoops#495]
getting the following error
 composer require flip/whoops 
  [InvalidArgumentException]
  Could not find package flip/whoops at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts
] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest
] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<pack
ages>]...

**Comment by denis-sokolov** [comment]
Use `filp/whoops`, not `flip/whoops`.

**Comment by brazitech** [comment]
haha   hey after 14 kids and 27 grand kids!!! you would FLIP instead of filp also.....lol
thanks for the typo correction!!!!
