### ISSUE TITLE
Change styling

### ISSUE THREAD

**Issue by tillkruss** [filp/whoops#500]
What's the best way to load an additional stylesheet or insert some inline styles?

**Comment by staabm** [comment]
into what? the prettypage handler?

**Comment by staabm** [comment]
the PrettyPageHandler has a method to load custom css
https://github.com/filp/whoops/blob/master/src/Whoops/Handler/PrettyPageHandler.php#L542

**Comment by tillkruss** [comment]
Yeah, thanks!
