### ISSUE TITLE
Compare with Tracy

### ISSUE THREAD

**Issue by landsman** [filp/whoops#506]
Hello,

do you know about [Tracy](https://github.com/nette/tracy)? 
Can you say what is better in Whoops?

Thanks

**Comment by denis-sokolov** [comment]
We’re not competing with Tracy. I believe Tracy has more features and is more actively maintained than Whoops. Perhaps the sole advantage of Whoops is our aesthetic choices about the looks of an exception screen. :-)

**Comment by staabm** [comment]
yep, we are the cool kids from the block. no further differences ;-)
