### ISSUE TITLE
blacklisting value with array causes error

### ISSUE THREAD

**Issue by fatcat386** [filp/whoops#507]
Hello!
strlen call in masked() method of PrettyPageHandler causes error if value is array. This function works only for string, not mixed type.
Please, add type check or add static "*****".
Or it could be another option - add ability to disable var dump completely.
Or shorten dump. $_SESSION vars contain long binary data in my case (thanks to some third-party library) and loading PrettyPage takes ages - this is why i use blacklist.
Or add ability to prohibit dump $_SESSION completely (with other superglobals perhaps).
Or change private method masked() to protected (for subclassing purposes).

Thank you!!!

**Comment by SvenRtbg** [comment]
This is related to #494, and this feature was added to the welcome list https://github.com/filp/whoops/wiki/Possible-features-to-add
