### ISSUE TITLE
Content negotiated whoops

### ISSUE THREAD

**Issue by shadowhand** [filp/whoops#508]
The application that I use Whoops in contains both HTML and JSON output. It would be fantastic if I could do the following:

```php
$whoops->pushHandler(new PrettyPageHandler());
$whoops->pushHandler(new JsonResponseHandler());
```

And depending on the `Accept` header of the request either pretty page or JSON would be output.

I imagine the most logical way to implement this would be as a `NegotiatedHandler` that would take a list of handlers, with a method like `setAcceptHeader($accept)` that would then choose the correct handler to use.

Would this functionality be useful to others?

**Comment by staabm** [comment]
I like a feature like this. IMO acceptance would depend on the amount of code required (as whoops should stay a 0 dependency project)

**Comment by WDD-Marv** [comment]
We're currently doing something with this, but there's a rare snafu that can result in *no* handler being applied.

built-in support would be nice :)

**Comment by chrisharrison** [comment]
My opinion is that the logic about which handler to use should be in the application layer based on the current environment. For example, the bootstrapping code should inject Whoops into an IoC container and inject it with the correct handler based on HTTP accept headers / environment variables or whatever.

It seems to me that putting that application/environment logic inside Whoops itself is too tightly coupled and breaks the inversion of control principle.

**Comment by staabm** [comment]
I agree with @chrisharrison and changed my stance on this topic. Negotiations should not be part of whoops👍

**Comment by shadowhand** [comment]
There was actually a similar issue over on [booboo](https://github.com/thephpleague/booboo/pull/39) and the discussion was quite interesting. I am going to say that this functionality is not appropriate for Whoops and should be handled by bootstrap and/or dependency injection.
