### ISSUE TITLE
PlainTextHandler: Customizable dump function

### ISSUE THREAD

**Issue by zonuexe** [filp/whoops#509]
The current implementation dumps value using `var_dump()`.
However, I would like to output by any function (eg. [`var_export()`](http://php.net/manual/function.var-export.php), [Symfony VarDumper](https://symfony.com/doc/current/components/var_dumper.html)).

The following code is a proposal by adding `PlainTextHandler::setDumper()`:

```php
$handler = new \Whoops\Handler\PlainTextHandler();
// PHP 7.1+
$handler->setDumper(Closure::fromCallable('var_export'));
// PHP 5, PHP7.0
$handler->setDumper('var_export');

$whoops = new \Whoops\Run;
$whoops->pushHandler($plain_text_handler);
```

**Comment by staabm** [comment]
Btw: the symfony var-dumper is already supported

**Comment by zonuexe** [comment]
@staabm 
Yes.  Symfony\VarDumper has `VarDumper::dump()` method that can be extended by users.

We can not use that method for `PlainTextHandler`.  There is a possibility that [HtmlDumper](https://github.com/symfony/var-dumper/blob/master/Dumper/HtmlDumper.php) is registered, so it may break the display as plain text.

**Comment by zonuexe** [comment]
We can transition the default dumper from `var_dump()` to `Symfony\VarDumper`. However, it was not included in this proposal to keep compatibility.

**Comment by staabm** [comment]
I guess a PR for this feature would be welcome
