### ISSUE TITLE
Installation README not clear enough

### ISSUE THREAD

**Issue by odannyc** [filp/whoops#511]
What exactly does this mean? "in your code", but where? What file? Any references? This is way too vague. I think the readme should be updated.

```
Register the pretty handler in your code:

$whoops = new \Whoops\Run;
$whoops->pushHandler(new \Whoops\Handler\PrettyPageHandler);
$whoops->register();
```

Thanks.

**Comment by GrahamCampbell** [comment]
> "in your code", but where? What file? Any references?

Depends what your code looks like.

**Comment by odannyc** [comment]
@GrahamCampbell 
Sorry, thought this was strictly a Laravel package.
Either way, I'm using Laravel, where would I register this?

**Comment by odannyc** [comment]
Figured it out:

https://mattstauffer.co/blog/bringing-whoops-back-to-laravel-5

**Comment by GrahamCampbell** [comment]
Or, you can use my exceptions package. :)
