### ISSUE TITLE
Difference in plain text?

### ISSUE THREAD

**Issue by juliangut** [filp/whoops#518]
What is the difference

https://github.com/filp/whoops/blob/master/src/Whoops/Handler/PrettyPageHandler.php#L210
https://github.com/filp/whoops/blob/master/src/Whoops/Handler/PrettyPageHandler.php#L244

Why not use the same strategy in both cases? can it be extracted into a protected method  so it can be overridden?

**Comment by denis-sokolov** [comment]
I think you have spotted a good potential improvement! I would drop `Formatter:formatExceptionPlain` and move the use to do `$plainTextHandler->generateResponse`. A PR is welcome!
