### ISSUE TITLE
Context sensitive suggestions on undefined method/variable/property

### ISSUE THREAD

**Issue by staabm** [filp/whoops#522]
Add a tracy like feature which suggests context sensitive help based on the current scope

See https://github.com/nette/tracy/blob/d9b4bf6c8ce10c06a84f0143a9608b2c192658db/src/Tracy/Helpers.php#L167

![img_1011](https://user-images.githubusercontent.com/120441/29382460-e58c4024-82cc-11e7-90f3-016999f38e18.PNG)

**Comment by staabm** [comment]
vscode added a more sophiscated algorithm to provide better suggestions in their December 2017 Release, see https://github.com/Microsoft/vscode/blob/114adf703be6203fba2da696aeac439449241ac9/src/vs/base/common/filters.ts#L710

**Comment by denis-sokolov** [comment]
This is an advanced feature that I expect will see little use. Still, I would be open for a well-designed PR for it.
