### ISSUE TITLE
Css hide content

### ISSUE THREAD

**Issue by Benfarhat** [filp/whoops#529]
## What am I asking for

**.frame-code div hide messages** and limit content to 23 lines or 345px (for code and args/comments)

## Detailed Description

I need to display all the arguments shown in the frame-code, and the fact that i can expand the content on demand by clicking on the arrow is a good thing, but even if it is expanded, a large part of my arguments containing tables also expandable (with the arrow link) is invisible.
To see the message, I always have to manually change css value with browser inspector

## Possible Implementation

- 1 - **Deleting height limit** [line](https://github.com/filp/whoops/blob/master/src/Whoops/Resources/css/whoops.base.css#L231) in [whoops.base.css](https://github.com/filp/whoops/blob/master/src/Whoops/Resources/css/whoops.base.css) solve the problem, 

We don't risk to have big huge page cause by default 
- code view limite the number of line to [40](https://github.com/filp/whoops/blob/master/src/Whoops/Resources/views/frame_code.html.php#L24) `$range = $frame->getFileLines($line - 20, 40);`
- arguments view collapse array content

```
    .code-block {
      /* max-height: 345px; <-- remove this line */
      overflow: hidden;
      padding: 10px;
      margin: 0;
      border-radius: 6px;
      box-shadow: 0 3px 0 rgba(0, 0, 0, .05),
                  0 10px 30px rgba(0, 0, 0, .05),
                  inset 0 0 1px 0 rgba(255, 255, 255, .07);
      -moz-tab-size: 4;
      -o-tab-size: 4;
      tab-size: 4;
      }
```

- 2 - Or **change overflow value from hidden to auto**, but the risk is to display multiple scrool-bar (for each part), and i'm not sure that's a good ux solution
```
    .code-block {
      max-height: 345px; 
      overflow: auto; /* <-- change this value */
      padding: 10px;
      margin: 0;
      border-radius: 6px;
      box-shadow: 0 3px 0 rgba(0, 0, 0, .05),
                  0 10px 30px rgba(0, 0, 0, .05),
                  inset 0 0 1px 0 rgba(255, 255, 255, .07);
      -moz-tab-size: 4;
      -o-tab-size: 4;
      tab-size: 4;
      }
```

**Comment by denis-sokolov** [comment]
It’s a complex issue that I’m not sure how well we’d solve long-term. Hopefully you’ve got a workaround and it does not affect anyone else. 🤷‍♂
