### ISSUE TITLE
Add Constants for editors

### ISSUE THREAD

**Issue by ximex** [filp/whoops#535]
I think it would be an improvement if there were constants for the supported editors

**Comment by staabm** [comment]
what do you mean? what would this constant provided? when do you need those? which problem should they solve?

**Comment by ximex** [comment]
It's not a problem. I think it's only more clear.
Code example:
```php
class PrettyPageHandler extends Handler
{
    const EDITOR_SUBLIME = "sublime";
    // ...
}

// somewhere in code
$handler->setEditor(PrettyPageHandler::EDITOR_SUBLIME);
```

**Comment by denis-sokolov** [comment]
This is a good suggestion. If anyone is up to implement it, I would be open to accept a PR. For now, I will be closing this issue.

We keep the list of the most interesting features to add in our Wiki:
https://github.com/filp/whoops/wiki/Possible-features-to-add
