### ISSUE TITLE
Prettify.js

### ISSUE THREAD

**Issue by khalilst** [filp/whoops#539]
In some countries cloudflare is not working and it's filtered.
So whoops doesn't work there.
file `whoops.base.js` line number 35, it loads prettify.js:
`  getScript('//cdnjs.cloudflare.com/ajax/libs/prettify/r298/prettify.js', function () {
    renderCurrentCodeblock();
  });
`

It will be nice, if the path is optional and maybe load it from a path defined in `.env` file with default value.
Appreciate it :)

**Comment by staabm** [comment]
Prettify was embedded into whoops with https://github.com/filp/whoops/commit/ad2bd7d6d428b42cf495354e48c164c6025da24d which renders this issue obsolete, I guess?
