### ISSUE TITLE
Enabling "Open Files In An Editor" in Laravel?

### ISSUE THREAD

**Issue by sunscreem** [filp/whoops#541]
Hi Folks.
I can't seem to find an obvious answer to this, but is it possible to easily enable this feature in a 5.5 app?

**Comment by adampatterson** [comment]
I was just about to open this as well. I looked back over my older 5.x changes and put the same config back into my 5.5 app and it worked fine for me.

https://github.com/filp/whoops/blob/master/docs/Open%20Files%20In%20An%20Editor.md

I recall adding some setup to `render()` under the exception handler.

```
        if (config('app.debug') && app()->environment() != 'production') {
            return $this->renderExceptionWithWhoops($request, $exception);
        }
```

Then I added 

```
protected function renderExceptionWithWhoops($request, Exception $exception)
    {
        $whoops = new \Whoops\Run;
        if ($request->ajax()) {
            $whoops->pushHandler(new \Whoops\Handler\JsonResponseHandler());
        } else {
            $handler = new \Whoops\Handler\PrettyPageHandler();
            $handler->setEditor('phpstorm');
            $whoops->pushHandler($handler);
        }

        return new \Illuminate\Http\Response($whoops->handleException($exception), $exception->getStatusCode(),
            $exception->getHeaders());
    }
```

**Comment by sunscreem** [comment]
Nice - Thank you sir!

**Comment by adampatterson** [comment]
@sunscreem  I will post a fix in a while once I get to work, I ran into an issue with composer update.

**Comment by adampatterson** [comment]
Hello @sunscreem 

My previous example worked until I did a Composer update, I got an error

```
[ErrorException]
  Declaration of App\Exceptions\Handler::renderExceptionWithWhoops($request,
  Exception $exception) should be compatible with Illuminate\Foundation\Excep
  tions\Handler::renderExceptionWithWhoops(Exception $e)
```

Here is the Gist that I came up with https://gist.github.com/adampatterson/1c01aec54ebce7632bddd9e9e8566a65

Because `renderExceptionWithWhoops` no longer accepts `$request` I created a handler called `handleWhoopsies` and let it do the split for me.

Everything seems to work great.
