### ISSUE TITLE
Whoops causing errors to be silent when running in docker container

### ISSUE THREAD

**Issue by bitwombat** [filp/whoops#544]
I've done a bunch of tracing, but I can't yet provide a testcase.

I've got a ZF3 app that's using Whoops.  When running from the command line, PHP runs out of memory and see a stack trace on STDOUT.  Run::handleException doesn't get called.

When I run the same thing inside a docker container, Run::handleException does get called, the PlainTextHandler gets involved, and I get nothing on STDOUT.  I see Run::writeToOutputNow is also getting called, so I should be getting something to STDOUT.  Other output from the test run is coming out on STDOUT.

Any ideas why or what I should do next?

**Comment by bitwombat** [comment]
You know what it is... this is an out of memory error, so running more code is sort of a bad strategy... I think one of the handlers Whoops is trying to run runs out of memory AGAIN, quitting the php process before my tester can run ob_end and get STDOUT out to the screen.

Should Whoops handle out of memory errors differently because of that?

**Comment by denis-sokolov** [comment]
Yes, but this is an advanced feature that I expect will see little use. Still, I would be open for a well-designed PR for it.
