### ISSUE TITLE
Add multiple frame types beside Application

### ISSUE THREAD

**Issue by DanielSiepmann** [filp/whoops#549]
Just because it's possible.

One should be able to define an identifier beside the path which is used as a selection. Possible use case:

"Application", "Plugins/Extensions/Bundles", "3rdParty"
They can be set to match laravel, symfony or any other framework, there packages, e.g. custom ones, and 3rd party libraries, e.g. from vendor.

By providing this feature one can customize this to his own needs to filter for specific areas.

**Comment by staabm** [comment]
maybe this makes sense, when we do it in a way the firefox javascript debugger does.

the firefox debbuger recognized some/popular frameworks and indicates those with an icon, see e.g.
https://twitter.com/jasonlaster11/status/921754572238049280
https://twitter.com/jasonlaster11/status/924018714810486786

**Comment by denis-sokolov** [comment]
This is a good suggestion. If anyone is up to implement it, I would be open to accept a PR.

We try to keep the outstanding issues under control, so I will be closing this, as until someone implements this, there is no action to be done. I’ve added this on [the list of possible features](https://github.com/filp/whoops/wiki/Possible-features-to-add).
