### ISSUE TITLE
Set error level in register

### ISSUE THREAD

**Issue by steffenk** [filp/whoops#559]
Hi,

i'm running whoops inside a framework. I can configure the error level in this framework and i want to have the same then in whoops.

I made small modifications like this:
$whoops = new \Whoops\Run;
$whoops->pushHandler(new \Whoops\Handler\PrettyPageHandler);
$whoops->register(4096);
where 4096 represents the error level.

Therefor i changed the signature of register:
 public function register($types = 'use-php-defaults')
and inside:
$this->system->setErrorHandler([$this, self::ERROR_HANDLER], $types);

Would be very handy if this change can make it :)

**Comment by denis-sokolov** [comment]
You should be able to use the built-in error_reporting function to achieve the same goal!
