### ISSUE TITLE
Security hole

### ISSUE THREAD

**Issue by vbarbarosh** [filp/whoops#571]
By default it dumps `_SERVER` and `_ENV` variables. Usually they contain a lot of sensitive information such as credentials for database and amazon services to name a few. The only _standard_ way to prevent this was `blacklist` variable, but

1) It doesn't allow to remove this sensitive variables entirely - I think it is unacceptable to show such variables at all. Only a few people should now their names.

> Blacklisted values will be replaced by **a equal length string** cointaining only '*' characters.

2) It forces to enumerate all of such variables one by one... It is so simple to forget about this after adding something new into .env file.

Much better decision whould be to not dump this variables by default, and to allow some way to include them when necessary. It's more secure out of the box.

**Comment by lukeberry99** [comment]
Whoops is a great tool for debugging, but should never be used in a production / publicly accessible sites.

I'd recommend only using whoops in local development / a test server with limited access (only those who should be able to see such things).

**Comment by vbarbarosh** [comment]
I agree with you @lukeberry99, but it's not always possible or reasonable. Currently I have to use dev version of an app, which is accessible to the public internet. This makes testing on different devices much easier than if it was under [basic auth](https://en.wikipedia.org/wiki/Basic_access_authentication).

This dev version have disabled registration page - which makes it impossible for new users to register. Only those who have been invited can login. Even then, in the case of exception, they can see only trace of exception without keys of AWS, MySQL, and other.

But after installing whoops everyone can get this keys by simply opening page like /asfasfasdfadfasd. At first I tried to fix this but found it too tricky. Instead of being as simple as overriding [PrettyPageHandler::masked](https://github.com/filp/whoops/blob/master/src/Whoops/Handler/PrettyPageHandler.php#L695) method (why is it *private*?), I have to adjust [searchPaths](https://github.com/filp/whoops/blob/master/src/Whoops/Handler/PrettyPageHandler.php#L552), then copy `views/env_details`, then modity it to discard "tables" `Server/Request Data` and `Environment Variables`.

**Comment by lukeberry99** [comment]
In a situation such as yours I would sacrifice ease of use for security - have the dev site under basic auth.

Another solution may be to have whoops only enabled for users that are logged in?

**Comment by tontonsb** [comment]
Is there any point in showing the equal-length string of asterisks? If variables are blacklisted, they should either be empty, get replaced with something uninformative (`[hidden]`) or just disappear from the list. No use in revealing length.

> In a situation such as yours I would sacrifice ease of use for security - have the dev site under basic auth.

This does seem a bit cumbersome that we have to set up and use the basic auth for every project just because we use whoops (which comes with laravel by default). Either that or turn off the Laravels debug mode (but it's useful for development). Or blacklist all the variables for each project which is cumbersome as well.

We develop on virtual servers and the projects are accessible on the internet since day 0.

There must be a whitelist approach available at least as an alternative - only show the the variables that you want to expose. I would say that whitelist should also be the only or at least the default approach instead of blacklisting.

**Comment by denis-sokolov** [comment]
There already exists a whitelist: if you start a PHP project, by default we don’t display your errors to the public. To make that happen you need to install and enable Whoops – a debugging feature meant for development.

**Comment by OwenMelbz** [comment]
I know this is old, but we're having a similar issue.

We've got a 3rd party script which uses Whoops, we cannot use basic auth to protect this as it's an API which already uses the Auth headers and such to authenticate users and we don't have access to internals.

Right now we either have "off" or "on" but this is our development site so we want it "on".

Is there actually a way to globally blacklist or prevent certain things being exposed in a situation like this?

Thanks

**Comment by denis-sokolov** [comment]
We have the “blacklist” feature you can find in the documentation. But beware that it is a convenience feature and not a security one. Whoops PrettyPageHandler is not meant to be exposed to the general public. =(

**Comment by denis-sokolov** [comment]
Alas. :-(
