### ISSUE TITLE
Cannot switch back to application frames

### ISSUE THREAD

**Issue by hubertnnn** [filp/whoops#573]
- Laravel Version: v5.6.20
- PHP Version: 7.1.16-1+ubuntu16.04.1+deb.sury.org+1
- Whoops version: 2.1.14

If I switch stacktrace from "Application frames" to "All frames" in Laravel whoops screen, its impossible to switch back.

More details here:
https://github.com/laravel/framework/issues/24176

**Comment by hubertnnn** [comment]
It seems that this only happens if "Application frames" are selected as default.
If "All frames" are the default tabs work fine.

eg. in Laravel a missing view error works fine, but if you throw an exception from controller, then the bug happens

**Comment by denis-sokolov** [comment]
Thanks for the report, fixed in the upcoming version!
