### ISSUE TITLE
include browsersync code 

### ISSUE THREAD

**Issue by snapey** [filp/whoops#574]
I'm looking for a way to add browsersync javascript code to the whoops page layout;

vendor/filp/whoops/src/Whoops/Resources/views/layout.html.php
 
This would allow browsersync to reload the page once the source that it is watching has been resaved.

I have proved it works by editing the above file directly, but this is not a good long term option.

In my case, Whoops is integrated with Laravel

**Comment by staabm** [comment]
Imo you should subclass the PrettyPageHandler

**Comment by kyuczer** [comment]
Hi, did you find any working solution?

**Comment by denis-sokolov** [comment]
I don’t think we’d want to accept custom JavaScript, but due to how PHP output works, I think you should be able to output a `<script>` tag before the Whoops output, right?
