### ISSUE TITLE
Missing an unshift handler method

### ISSUE THREAD

**Issue by tflori** [filp/whoops#580]
Because handlers may stop to execute other handlers I need to set the order correctly but most important handlers are added first in my application.

I'm initializing my application and whoops should handle all errors. And yet I don't know which handlers I want to register (is it a web page and the user is allowed to see error messages - then I want to register a PrettyPage handler; or it is a json request; or it is a cli interface) but all errors should everytime appear in a log. So at this stage I want to register a plain text handler with `loggerOnly(true)`.

But when I then register a pretty page handler it quits the execution of other handlers and so the error will not be logged.

My current workaround is to register the handlers with a helper function that has a confusing naming (of course `Run` is final so not in a subclass of `Run` where it should be):

```php
/**
 * Prepends $handler to the list of handlers from whoops.
 *
 * Because whoops executes the handlers in reverse order they will run as last handler - so they are appended.
 *
 * @param callable|HandlerInterface $handler
 */
public function appendWhoopsHandler($handler)
{
    $handlers = $this->whoops->getHandlers();
    array_unshift($handlers, $handler);
    $this->whoops->clearHandlers();
    foreach ($handlers as $handler) {
        $this->whoops->pushHandler($handler);
    }
}
```

**Conclusion**

In my opinion handlers should be executed in the order they are registered but that would mean a breaking change.

Wether a handler is the last one executed or not should be a decision from the developer not from the handle but changing this to `pushHandler($handler, $last = false)` would also mean a breaking change.

The simplest solution is to allow the developer to "append" a handler by giving him a `unshiftHandler($handler)` method (to keep array method naming).

In case you don't have time to develop this but would accept such a PR I can prepare one for you.

**Comment by denis-sokolov** [comment]
I agree that the handlers should be executed in the order they are registered. I would accept a PR which adds a proper `appendHandler` function and marks `pushHandler` as deprecated.
