### ISSUE TITLE
Filenames with spaces cannot be opened on linux

### ISSUE THREAD

**Issue by staabm** [filp/whoops#581]
When using the editor integration on a linux client and a filename contains a space which will be encoded , the resulting link doesnt work:

https://github.com/filp/whoops/blob/6b3abfd1a21cb180013e373b9b7ee5b64ffc6c3b/src/Whoops/Handler/PrettyPageHandler.php#L453

This seems to be a known problem, as the underlying tool seems to be unable to resolve %20 as a space, see https://unix.stackexchange.com/questions/169241/xdg-open-doesnt-handle-percent-encoded-file-urls-with-lxde

**Comment by bloep** [comment]
It seems that special characters generally cause problems. e.g. slashes.
A url like this `phpstorm://open?file=%2Fvar%2Fwww%2Fhtml%2Fredaxo%2Fsrc%2Faddons%2Fstructure%2Fplugins%2Fcontent%2Flib%2Farticle_content_base.php&line=416` doesn't work.

**Comment by staabm** [comment]
As per https://unix.stackexchange.com/questions/169241/xdg-open-doesnt-handle-percent-encoded-file-urls-with-lxde the expected format is a filepath, not a url when xdg-open is used.

**Comment by staabm** [comment]
As per our testing everything seems to work when removing the rawurlencode escaping.

**Comment by denis-sokolov** [comment]
Did you figure it out? You’ve closed the PR immediately. If you have more details, we’ll revisit this issue.
