### ISSUE TITLE
Collaborate with PsySH and make REPL

### ISSUE THREAD

**Issue by filips123** [filp/whoops#585]
You could collaborate with [PsySH](https://github.com/bobthecow/psysh) and make online REPL for PHP. See https://github.com/bobthecow/psysh/issues/505 and https://github.com/bobthecow/psysh/issues/505#issuecomment-402972140.

I know there is old issue for REPL in Whoops (#42), but it is very old and closed.

**Comment by jens1o** [comment]
That would be awesome!

**Comment by filips123** [comment]
Maybe you could use [Web Console](https://github.com/nickola/web-console) to access [PsySH](https://github.com/bobthecow/psysh).

**Comment by denis-sokolov** [comment]
This is a duplicate of #42.

**Comment by filips123** [comment]
@denis-sokolov Can you reopen #42 so it would receive more attention?

**Comment by denis-sokolov** [comment]
On this project a GitHub issue is a poor medium for a wishlist of features. It’s on the wiki: https://github.com/filp/whoops/wiki/Possible-features-to-add
