### ISSUE TITLE
Support source code preview when php codes is not executed from a file

### ISSUE THREAD

**Issue by staabm** [filp/whoops#586]
There are different use cases where the actual php code beeing run is not contained within a file.

In some applications some php source might be stored in e.g. database or in our concrere use-case the source is included via a php stream wrapper.

The current mechanics dont allow to render the code preview for those code frames.

I would like to request some kind of api which allows to find/fetch the actual source per frame for non-file-based source locations.

**Comment by gharlan** [comment]
Maybe a possibility to set a "frame handler" callback, which will be called for each frame.
This could be used [to add comments](https://github.com/filp/whoops/blob/e79cd403fb77fc8963a99ecc30e80ddd885b3311/src/Whoops/Exception/Frame.php#L133-L144) or to set the "file" content to bypass [this](https://github.com/filp/whoops/blob/e79cd403fb77fc8963a99ecc30e80ddd885b3311/src/Whoops/Exception/Frame.php#L133-L144).

**Comment by denis-sokolov** [comment]
That’s a fancy advanced feature that will see very little usage. Still, I would be open for a PR if it is carefully designed.
