### ISSUE TITLE
MacOS High Sierra + Safari

### ISSUE THREAD

**Issue by EvilLooney** [filp/whoops#589]
I noticed slow scrolling issues when using High Sierra (10.13.6 (17G2208)) and Safari (Version 11.1.2 (13605.3.8)). I can clearly see the GPU is maxed out when viewing it inside the Activity Monitor.

Granted this looks like a Safari Webkit bug as Chrome does not display this behaviour, but I managed to pinpoint the problem CSS:
https://github.com/filp/whoops/blob/e79cd403fb77fc8963a99ecc30e80ddd885b3311/src/Whoops/Resources/css/whoops.base.css#L233

Is this line needed at all? Or better yet, is there anyway to overload the CSS?

I am using Laravel 5.6.

Thank you.

**Comment by denis-sokolov** [comment]
This seems to be a corner case in that Safari version. Even if we were to remove the style line, we may in the future add another unknowingly. You can output your own styles with a `<style>.selector{border-radius: 0 !important}</style>` before Whoops runs if you wish.
