### ISSUE TITLE
Arguments list shows resource ID instead of var_dump

### ISSUE THREAD

**Issue by idontusenumbers** [filp/whoops#591]
It would be useful if the arguments in the stack frame screen shows var_dumps of objects instead of their resource ID (assuming I'm reading this stuff right).

**Comment by staabm** [comment]
The latest releases shoud use the symfony var-dumper when available. 

I guess thats what you are after

**Comment by idontusenumbers** [comment]
What version of whoops? How is that configured/utilized? Are there config values or setup steps?

**Comment by staabm** [comment]
Was the referenced feature the thing you searched for? If so, Can you close the issue then?

**Comment by idontusenumbers** [comment]
I haven't had a chance to check but I suspect that it does. Thanks!
