### ISSUE TITLE
message from previous exceptions missing

### ISSUE THREAD

**Issue by geromueller** [filp/whoops#593]
Please concat the message of the previous exceptions. currently only the stack frames are collected. The messages are even more important!

**Comment by denis-sokolov** [comment]
This is a good suggestion. If anyone is up to implement it, I would be open to accept a PR.

For future reference, added this to [the wiki page of possible features](https://github.com/filp/whoops/wiki/Possible-features-to-add).

**Comment by denis-sokolov** [comment]
Done in #596!
