### ISSUE TITLE
file_get_contents([internal]): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by lcharette** [filp/whoops#598]
We're encountering a `file_get_contents([internal]): failed to open stream: No such file or directory` error in our implementation of whoops. After some digging, it goes back to the changes made in https://github.com/filp/whoops/commit/4798f07fc8987457073a2184cbef0afdc4d54fdb.

The `[internal]` part is returned by the [`Inspector`](https://github.com/filp/whoops/blob/master/src/Whoops/Exception/Inspector.php#L181). Removing the superfluous `is_file()` check doesn't really make sense if a file can be set as `[internal]` and won't be catched by the other checks. 

A proposed fix would be to revert changes made in https://github.com/filp/whoops/commit/4798f07fc8987457073a2184cbef0afdc4d54fdb.

**Comment by staabm** [comment]
Can you describehow to reproduce this problem?

**Comment by lcharette** [comment]
I managed to replicate in a fresh clone of this repo by changing this line : https://github.com/filp/whoops/blob/master/tests/Whoops/Handler/PrettyPageHandlerTest.php#L21

To : 
```
$handler->handleUnconditionally(true);
```

Same happens if you change the default property to true ( `private $handleUnconditionally = true;` )

**Comment by denis-sokolov** [comment]
Fixed in #599!
