### ISSUE TITLE
Add debugger bar

### ISSUE THREAD

**Issue by filips123** [filp/whoops#601]
Add some debugger bar which shows some debugging information like messages, errors, request, response, database. How could also integrate XDebug and Zend Debugger.

It should be something like [Zend Z-Ray](http://www.zend.com/en/products/server/z-ray) and [Tracy](https://github.com/nette/tracy). Maybe they could also be integrated in Whoops.

You could use [PHP Debug Bar](http://phpdebugbar.com/) for this.

**Comment by SvenRtbg** [comment]
Is this a good fit or addition for the task Whoops delivers?

The PhpDebugBar demo already has an exception catch tab with info. Seems like it is the same thing with different layout. So one would either use the debug bar or Whoops, wouldn't one?

**Comment by denis-sokolov** [comment]
This is very broad and abstract. Even if we narrow it down, we don’t have the resources to add this functionality until someone comes in with more concrete PRs. So thanks for the suggestion, but nothing we can do.
