### ISSUE TITLE
Extra exception details in JsonResponseHandler and XmlResponseHandler

### ISSUE THREAD

**Issue by kktsvetkov** [filp/whoops#603]
Occasionally exception classes do host an exception code, that is stored inside [\Exception::$code](http://php.net/manual/en/class.exception.php#exception.props.code).

Also, when using [\ErrorException](http://php.net/manual/en/class.errorexception.php), this type of exception class hosts the [severity](http://php.net/manual/en/class.errorexception.php#errorexception.props.severity) (its "error level" or "error type") of the logged error event.

In both these cases with JsonResponseHandler and XmlResponseHandler the data is provided from [Formatter::formatExceptionAsDataArray()](https://github.com/filp/whoops/blob/master/src/Whoops/Exception/Formatter.php#L18) method. Perhaps the $response returned there must include these two exception properties (code and severity) if they are indeed set inside the reported Exception.

**Comment by denis-sokolov** [comment]
This is a good suggestion. If anyone is up to implement it, I would be open to accept a PR.

We try to keep the outstanding issues under control, so I will be closing this, as until someone implements this, there is no action to be done.
