### ISSUE TITLE
Whoops page shows no text

### ISSUE THREAD

**Issue by tunedin76** [filp/whoops#607]
After a composer update, My whoops page no longer shows any text.
![screencapture-wolfs-legacyassuranceplan-import-2018-11-30-08_43_20](https://user-images.githubusercontent.com/16789318/49292725-0d3ca380-f47c-11e8-9463-0dc78148febb.png)

**Comment by tunedin76** [comment]
![screencapture-wolfs-legacyassuranceplan-import-2018-11-30-08_44_35](https://user-images.githubusercontent.com/16789318/49292796-3e1cd880-f47c-11e8-93d6-5c504139d320.png)

**Comment by denis-sokolov** [comment]
I’m sorry, this does not seem to be a clearly described issue. Given your description, it is tricky to figure out what went wrong. Perhaps you should first try other avenues of action, such as investigate the problem further, ask for help on support forums. You could also try to come up with a simpler way to reproduce your problem on a website like jsfiddle.net. If you have new findings, by all means, feel free to add them here and the issue might be reopened.
