### ISSUE TITLE
PlainTextHandler does not show previous exceptions

### ISSUE THREAD

**Issue by tflori** [filp/whoops#608]
I'm not sure if I should open two issues and before I spam this really nice project I wanted to ask the maintainers what they think about it.

The initial problem I had is that somewhere in the code an exception can be catch and replaced with another exception. Ideally the exception contains the previous exception that caused this exception.

For example an ORM catches the PDO exception and throws an ORM specific exception. I'm ok with this approach and I don't think the ORM specific exception should include the message from the PDO exception but it should have the previous exception. But with PlainTextHandler I only get the uncaught exception.

Now just because I don't wanted to bother you I wanted to extend the PlainTextHandler to lets say a DetailedPlainTextHandler. But what I really don't like is to copy paste  the exact same method just because it is private and so I'm writing here because `PlainTextHandler::getTraceOutput()` is private so I can't just extend the PlainTextHandler.

I would love to add the option `PlainTextHandler::addPreviousToOutput()` that is just adding all messages followed by the stack trace. Example output:

```
ORM\Exception: Error preparing the fetch statement for App\Model\User in file /path/to/orm.php on line 23
Before: PDOException: undefined table users in /path/to/orm.php on line 42
#1 ORM\Exception->() /path/to/orm.php:23
#2 PDO->prepare('...') /path/to/orm.php:42
#3 ORM\EntityManager->fetch('App\Model\...') /path/to/script.php:6
```

Would such a PR be accepted or is there already a similar PR or feature?

<small>p. s.: can someone please explain why `PlainTextHandler::getTraceOutput()` is private? It is nearly impossible to extend the class without having to write everything your own.</small>

**Comment by staabm** [comment]
IMO the plain handler should handle the concept of a „previous“ exception like we do in the PrettyPageHandler. I would love to have it.

**Comment by tflori** [comment]
but it would be a repeated stack trace or not?

**Comment by staabm** [comment]
I guess we should give it a try and see how it looks. Not sure right now
