### ISSUE TITLE
Support wildcard in blacklist variables

### ISSUE THREAD

**Issue by barryvdh** [filp/whoops#610]
To make it easier to blacklist certain variables, would it be a good idea to allow blacklists in variable names? eg. `*_PASSWORD`, `*_SECRET` etc? That would make it easier to set sensible defaults.

(Yes I understand, don't expose dev pages to public, but seeing as the blacklist is already here)

> Note: this is different from https://github.com/filp/whoops/pull/577 whereas that adds a wildcard to the type of variable, not the variable itself.

**Comment by SvenRtbg** [comment]
You should probably leave feature request tickets open until your pull request is finally merged - just IMHO.

**Comment by barryvdh** [comment]
Wouldn't that just create more noise and double discussion?

**Comment by SvenRtbg** [comment]
I don't know. As you can see, closing an issue does not prevent discussions.

My general perception is: The feature request would be used for discussing pros and cons of said feature, and maybe code changes on an abstract level, while the pull request has a very concrete code change and would be used to discuss it on a detailed level. Linking the two (as you did) will make the different discussions observable from each other. Merging the PR would resolve and close the feature request - if the PR isn't merged or is rejected, it does not reject the request for it, only its current implementation. The feature request stays open until it is either implemented differently, or rejected.

**Comment by denis-sokolov** [comment]
Thanks for a good suggestion! Unfortunately, the masking is a very low-priority feature and this grows its complexity further to uncomfortable levels. So barring a great PR as I discuss in #612, this is not a feature we are looking for.

**Comment by ajhalls** [comment]
I struggled with this too for a bit on a dev machine. my solution was to edit `vendor/filp/whoops/src/Whoops/Handler/PrettyPageHandler.php` and add in:

```
public function sanitizePrivate($data, $badwords){
    foreach ($data as $key=>$value) {
       
        foreach ($badwords as $keyword) {
               // dd($key);
            if (strpos(strtolower($key), $keyword) !== FALSE) {
                $data[$key] = "***************";
            }
        }
    }
    return $data;
}
```

This converts all the incoming data to lowercase and then searches for partial matches so you don't have to specify every variation of password variable names. Then in the handle() function, define terms you want to exclude.
```

$badwords = array("password", "pwd", "secret", "key", "token", "salt", "mail");
$_SERVER=$this->sanitizePrivate($_SERVER, $badwords);
$_ENV=$this->sanitizePrivate($_ENV, $badwords);

```
