### ISSUE TITLE
Add config file for exclusion of sensitive information

### ISSUE THREAD

**Issue by PieterjanDeClippel** [filp/whoops#614]
Would it be possible to implement a config file **whoops.php** so the developer can choose what information should be hidden from the whoops-page?

Preferably like this:

```
<?php

return [
    'default_mode'    =>    'hide',
    'expose_always'   =>    [
        'APP_NAME',
        'APP_URL',
    ],
    'hide_always'     =>    [
        'APP_KEY',
        'DB_DATABASE',
        'DB_USERNAME',
        'DB_PASSWORD',
        'REDIS_PASSWORD',
        'MAIL_USERNAME',
        'MAIL_PASSWORD',
        'PUSHER_APP_ID',
        'PUSHER_APP_KEY',
        'PUSHER_APP_SECRET',
        'MIX_PUSHER_APP_KEY',
        'ALGOLIA_APP_ID',
        'ALGOLIA_SECRET'
    ]
];
```

When a hacker hacks into a corporate network and finds a private development server, at least he wouldn't be able to read all third party credentials from the HTML page.
SQL credentials should already be different in dev <> prod environment, but you'd never know.
This way the developer is totally free to choose what's printed on the whoops-page (no passwords for example).

The configuration would let the developer choose to either allow/deny certain variables from being exposed on the Whoops-page...

**Comment by PieterjanDeClippel** [comment]
Implied by #613

**Comment by ajhalls** [comment]
I struggled with this too for a bit on a dev machine. my solution was to edit `vendor/filp/whoops/src/Whoops/Handler/PrettyPageHandler.php` and add in:

```
public function sanitizePrivate($data, $badwords){
    foreach ($data as $key=>$value) {
       
        foreach ($badwords as $keyword) {
               // dd($key);
            if (strpos(strtolower($key), $keyword) !== FALSE) {
                $data[$key] = "***************";
            }
        }
    }
    return $data;
}
```

This converts all the incoming data to lowercase and then searches for partial matches so you don't have to specify every variation of password variable names. Then in the handle() function, define terms you want to exclude.
```

$badwords = array("password", "pwd", "secret", "key", "token", "salt", "mail");
$_SERVER=$this->sanitizePrivate($_SERVER, $badwords);
$_ENV=$this->sanitizePrivate($_ENV, $badwords);

```
