### ISSUE TITLE
Is there any plans for i18n?

### ISSUE THREAD

**Issue by pipegris** [filp/whoops#619]
Hi!
Thanks for this awesome package. I was wondering if is there any plans for internationalization, and how could I begin to help, I could translate it to Spanish.

Thanks

**Comment by SvenRtbg** [comment]
I wonder where a translation would be really beneficial, as this is a developer tool. I'd make the bold assumption that developers should be able to understand a certain amount of english, and "whoops" does not really use much translateable text in the error page anyways. For documentation this might be a different story.

What is your perspective? Where would you like to see some text translated?

**Comment by pipegris** [comment]
Well, this is a fair point, I don't have any special issues with it being in English, I was just asking in case you needed a hand, but I guess you are right in the sense that is a developer tool and it's not final user oriented so it's not that important.
Thanks for your answer.
