### ISSUE TITLE
Integrating logging

### ISSUE THREAD

**Issue by unstoppablecarl** [filp/whoops#62]
What would be the best way to integrate error logging with whoops? Does whoops catch errors and convert them to exceptions or any other magic that would effect logging errors/exceptions?

**Comment by maicol07** [comment]
> 
> 
> Whoops can easily be integrated with a logger, using a custom handler. Here's a pretty simple example:
> 
> ```
> 
> $whoops = new Whoops\Run;
> 
> // Add some handlers
> $whoops->pushHandler(new Whoops\Handler\PrettyPageHandler);
> $whoops->pushHandler(new Whoops\Handler\JsonResponseHandler);
> 
> // Setup Monolog, for example:
> $logger = new Monolog\Logger;
> $logger->pushHandler(new Monolog\Handler\StreamHandler("/my/exception.log"));
> 
> // Place our custom handler in front of the others, capturing exceptions
> // and logging them, then passing the exception on to the other handlers:
> $whoops->pushHandler(function ($exception, $inspector, $run) use($logger) {
>     $logger->addError($exception->getMessage());
> });
> ```

@filp your code doesn't work anymore with Monolog 2. Could you update that?

**Comment by denis-sokolov** [comment]
@maicol07, that’s a comment that’s over 6 years old. :-)

Try pushing the logger handler above the other handlers.
