### ISSUE TITLE
Idea: Auto Save Whoops! screens as they come through on live sites

### ISSUE THREAD

**Issue by JonathanPort** [filp/whoops#623]
Hi, love this package. So nicely designed.

I'm in a situation where we have a live client site and occasionally we have minor exceptions that pop up for users. We have debug off on live (obviously) so the user sees our nicely designed error 500 screen. To capture the error we use Laravel Logging + Slack integration to feed error messages over to our Slack channel. This is great and gives us a stack of the error inside the channel but it's obviously poor to read and not as interactive as the Whoops screen. Makes it difficult to get to the bottom of the issue when it looks like this:

![log](https://user-images.githubusercontent.com/16456310/54483616-23fddf00-484e-11e9-84ae-d3731e12bb93.png)

So I was thinking it would be cool to be able to access these errors but in "Whoops! Format" at my convenience. Maybe some kind of page/route that you can access to view logs in a whoops format?

Alternatively an auto save feature that when an error is viewed by the user, it downloads it into storage as a .html file?

**Comment by SvenRtbg** [comment]
Whoops must not be used in production. It will reveal secrets like your code and its vulnerabilities or passwords stored in variables.

Everything Whoops does can be done in a way that only tells the user that there was an error, and store the details in a log file for you to investigate. But Whoops does explicitly not want to deal with this case, it's a development tool.

If you look at the issue tracker, there are plenty of issues requesting more secrecy, but I don't think this will ever be reliably possible.

Referencing #610, #604, #571, #507, #614, #481.

**Comment by kktsvetkov** [comment]
@JonathanPort you can save the exception object in serialized format and log it like that; when you want to view it,  you can unserliaze it and pass it to Whoops.

Here's an example
```php
$whoops = new \Whoops\Run;
$whoops->pushHandler(new \Whoops\Handler\PrettyPageHandler);
$whoops->register();

/* serialized exception wil be logged ...*/
$serialized_exception = serialize( new RuntimeException('Egati Probata!') );

/* ... and later when you want to view it, unserialize */
$ex = unserialize($serialized_exception);
$whoops-> handleException($ex);
```

**Comment by JonathanPort** [comment]
> Whoops must not be used in production. It will reveal secrets like your code and its vulnerabilities or passwords stored in variables. Everything Whoops does can be done in a way that only tells the user that there was an error, and store the details in a log file for you to investigate. But Whoops does explicitly not want to deal with this case, it's a development tool. If you look at the issue tracker, there are plenty of issues requesting more secrecy, but I don't think this will ever be reliably possible. Referencing #610, #604, #571, #507, #614, #481.

I don’t intend to view in a production environment obvs @SvenRtbg 



@kktsvetkov That is more or less what I needed, thanks very much! Didn’t know how you would do that, the docs aren’t the easiest to follow for me. This will come in very handy, thanks again

**Comment by denis-sokolov** [comment]
Great discussion, added to our docs:
https://github.com/filp/whoops/blob/master/docs/Replay%20Errors.md

**Comment by Madydri** [comment]
@JonathanPort  Maybe my question is obvious, but If I apply your example by just putting the code

`$whoops = new \Whoops\Run;
$whoops->pushHandler(new \Whoops\Handler\PrettyPageHandler);
$whoops->register();
/* serialized exception wil be logged ...*/
$serialized_exception = serialize( new RuntimeException('Egati Probata!') );`

in the file including whoops in our run, the PrettyPage is still displayed.
So for the beginner I am : where has 
`$serialized_exception = serialize( new RuntimeException('Egati Probata!') );`
to be put to avoid this ?
Do I have to modify the code PrettyPageHandler.php of Whooops for that ?

**Comment by kktsvetkov** [comment]
@Madydri it all starts at `RunInterface::handleException()`, so you can either create your own implementation using that interface, or you can extend `Run` class like this:

```php 
use Whoops\Run;

class RecordRun extend Run
{
    function handleException($exception)    
    {
        ThisIsWhereWeAreRecordingTheException( serialize($exception) );
        return parent::handleException($exception);
    }
}

```

This is a very crude example though, as in most projects there are better ways to log exceptions, which I assume happens BEFORE they are visualized with Whoops. So look into the project you are using to find out how are errors/exceptions logged, and look for a place where to add this "saving of the exception".
