### ISSUE TITLE
Bug when Phalcon using

### ISSUE THREAD

**Issue by TimurFlush** [filp/whoops#626]
Hello.

I use a Phalcon framework and when an exception is thrown inside the framework, PrettyPageHandler generates the following error:

File: Whoops/Exception/Frame.php
Line: 122

```
Whoops \ Exception \ ErrorException (E_ERROR)
Uncaught Whoops\Exception\ErrorException: file_get_contents(phalcon/crypt.zep): failed to open stream: No such file or directory in /home/mysite/vendor/filp/whoops/src/Whoops/Exception/Frame.php
```

Please fix it

**Comment by gnumoksha** [comment]
This error happens because Phalcon is loaded as a C extension, so none of its files will exist locally.

As workaround you can create a new Handler that will ignore Phalcon's exceptions.

**Comment by TimurFlush** [comment]
Thank you, @gnumoksha

**Comment by gnumoksha** [comment]
@TimurFlush please, note that I was not saying that is not a bug and/or can't be solved. I was only posting an explanation.

I can help with the patch, but I'm unable to reproduce the described behavior.

**Comment by TimurFlush** [comment]
@gnumoksha 
I can help myself too, but I think that it must be realised by library developers.
Mind you, that's just my opinion.
