### ISSUE TITLE
Whoops sitewide?

### ISSUE THREAD

**Issue by PwrSrg** [filp/whoops#636]
This is probably a stupid question, but how do I get Whoops to work throughout my entire site?
Do I need to add all of the [require/new/pushHandler/register] code to the top of EVERY page?

Thanks!

**Comment by staabm** [comment]
It needs to be part of your bootstrapping logic, so basically - yes

**Comment by denis-sokolov** [comment]
At the very least you can extract your bootstrapping logic into a separate file, so all you need to do is `require "my-error-handler.php"`.

A good practice in PHP is to handle all requests through one entry point anyway, so that’s when those sites would configure Whoops.
