### ISSUE TITLE
dump function arguments with PrettyPageHandler

### ISSUE THREAD

**Issue by Druid33** [filp/whoops#642]
Hi, i use PrettyPageHandler to display errors in my application. I think, its awesome library.

In stacktrace, bellow code i expected function arguments to be displayed. Its ok for primitive types. But for objects Whoops display only type of object instead of expandable dump of variable.

What i see:
![image](https://user-images.githubusercontent.com/6436809/67264837-8d149780-f4ac-11e9-85f3-0850daa4dbae.png)

What i expected:
![image](https://user-images.githubusercontent.com/6436809/67264858-9b62b380-f4ac-11e9-9cf1-10ed81d87a0d.png)

I dig into tho code and find, that if i comment adding Casters to Cloner in PrettyPageHnadler->__construct() method, i get output i expected.
https://github.com/filp/whoops/blob/cde50e6720a39fdacb240159d3eea6865d51fd96/src/Whoops/Handler/PrettyPageHandler.php#L145

Its a future or its a bug? :)

**Comment by denis-sokolov** [comment]
It does, indeed, look like a bug. Thank you for reporting this!

Somebody will take a look at it and hopefully we’ll get it fixed properly.

**Comment by denis-sokolov** [comment]
I’ve now found out this is on purpose, as dumping everything indiscriminately did not allow us to maintain the level of performance we expect. See #401 and #404!

Thanks for bringing it up, if anyone comes up with an improvement, let us know.

**Comment by Druid33** [comment]
Hi, again.

First sorry for reopening ticket. 

I use PrettyPageHandler with commented line i mention in ticket description for 5 months without performance issues. I know...its only my case.

The problem is, that i cant extend PrettyPageHandler and use my own cloner instance, because cloner is set in constructor. So i copy-paste that class and make lot of dirty changes to make it run.

Now, i start new project, i like to have function arguments dumped, but i dont wont make dirty copy-paste "solution" again.

It will be fine have chance make it clean. Is it possible to make simple protected setCloner() method on PrettyPageHandler?

```php
protected setCloner($cloner) 
{
    $this->templateHelper->setCloner($cloner);
}
```

I thing thats enough for everyone, who can dump funcion argument in PrettyPageHandler.

**Comment by Druid33** [comment]
..or just make $templateHelper property protected instead of private.
```php
/**
* @var TemplateHelper
*/
protected $templateHelper;
```
