### ISSUE TITLE
Handlers always marked as CSS active after refactoring

### ISSUE THREAD

**Issue by TysonAndre** [filp/whoops#646]
This was introduced in a5ca015a59f93bc5c63ba92bbf05b17e7956d8d3

https://github.com/filp/whoops/blob/c25bbbcedc4ab3d64e3c82896ba2ac766397d34c/src/Whoops/Resources/views/env_details.html.php#L36

`$handlers === $handlers` is always true for an object. (Aside: It'd only normally ever be false for `NAN`.)

I'm not familiar with what this should be checking against instead.

- I think there'd be a global variable $handler that got clobbered by the loop variable - renaming the loop variable is probably how you'd fix this.

Noticed with static analysis(Phan)

**Comment by denis-sokolov** [comment]
Thank you, this is all precisely right!
