### ISSUE TITLE
Display exception error code in PrettyPageHandler

### ISSUE THREAD

**Issue by RickWong** [filp/whoops#65]
We use HTTP Status Codes as exception error codes in our API controllers (40x). When such an exception is thrown, and intentionally not caught in development, it would be nice to see the error code somewhere in the PrettyPageHandler!

**Comment by adduc** [comment]
I believe #212 resolves this issue. Can this issue be closed?

**Comment by staabm** [comment]
Agree.

**Comment by RickWong** [comment]
BOOM! Closed.
