### ISSUE TITLE
Output HTML miss formatted 

### ISSUE THREAD

**Issue by kevindees** [filp/whoops#651]
I'm using v2.5.1 and it seems like there is an HTML formatting issue. When I get an error and through an exception, I get this as the error:

<img width="767" alt="Screen Shot 2019-12-23 at 10 38 35 AM" src="https://user-images.githubusercontent.com/348368/71366591-69370600-2570-11ea-8a20-b85e7ed004a3.png">

I've dug in a little bit and it seems like the issue is someplace in the `$panel_left_outer` but I have not had time to look deeper. I'm not sure if this is a common issue or if I should keep digging around.

This error specifically happens when there I use `throw new \Exception('hi');` or simular but other errors like syntax errors, `syntax error, unexpected 'if' (T_IF)`, do not have this issue.

Note, this error happens when HTML has already been output to the page. I'm using a custom layout to remove the original HTML.

Maybe an unclosed div?

Thanks,
Kevin

**Comment by GrahamCampbell** [comment]
What version of PHP is the web server itself running?

**Comment by kevindees** [comment]
```
PHP 7.3.4-1+ubuntu18.04.1+deb.sury.org+3 (cli) (built: Apr 10 2019 10:51:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.4, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.4-1+ubuntu18.04.1+deb.sury.org+3, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.1, Copyright (c) 2002-2019, by Derick Rethans
    with blackfire v1.24.4~linux-x64-non_zts73, https://blackfire.io, by Blackfire
```

**Comment by staabm** [comment]
Is this a recent regression? Did it work with 2.5.0 for you on this very same server?

**Comment by GrahamCampbell** [comment]
@kevindees Is your web server definitely the same version? php cli might not necessary be the same ascphp fpm.

**Comment by kevindees** [comment]
It is, I’m using Laravel Homestead. Codebase is WP.

**Comment by kevindees** [comment]
Hey @GrahamCampbell 

I run the code through the HTML 5 validator and everything passed. Turns out you need to add `ob_start()` to the `wp-config.php` WordPress file to make it work as expected.

Thanks,
Kevin
