### ISSUE TITLE
Add Support for Corner Messages

### ISSUE THREAD

**Issue by paragonie-security** [filp/whoops#652]
We intend to follow up this issue with a pull request, if there is community interest. The purpose of this issue is to assess whether or not there is community interest.

[paragonie/corner](https://github.com/paragonie/corner) provides an interface and an accompanying trait to offer an [extended API](https://github.com/paragonie/corner#corners-extended-exception-api) to facilitate [high-quality error messages](https://twitter.com/acfoltzer/status/1074813646625169408).

If there is any interest, we'd like to send a pull request that automatically exposes the helpful messages if the exception caught by whoops implements `CornerInterface`.

... And that's pretty much it!

What do you think? We want to make PHP error handling more helpful to developers. This should align well with the goal of Whoops.

**Comment by staabm** [comment]
I like the idea. Would be great to see a example how this would look like UI wise and how the DD would improve in this situation in comparison what we have right now

**Comment by staabm** [comment]
E.g. will the corner lib provide some means to enhance php-src native errors to provide higher quality error messages like the one you pointed out in https://twitter.com/acfoltzer/status/1074813646625169408 ?

**Comment by paragonie-security** [comment]
Not by itself, no. You'd have to have an error handler or exception handler that looks at the error message (especially function name) and uses `getSnippet()` to show the developer what they're doing wrong.

**Comment by denis-sokolov** [comment]
Whilst we would benefit from more helpful messages, the hard part is creating the messages, not the infrastructure surrounding them. If it works out, it’d be fun to include them in Whoops, of course.
