### ISSUE TITLE
Using monolog and whoops

### ISSUE THREAD

**Issue by BryanYeh** [filp/whoops#654]
I am trying to using Monolog in the ``set_exception_handler`` and ``set_error_handler``, while Whoops outside.

I tried 2 locations for running Whoops.

 1. ``Run Whoops #1 Location``
     - Result: Monolog logs the error/exception and Whoops doesn't display
 2. ``Run Whoops #2 Location``
     - Result: Monolog doesn't log anything and Whoops displays

I am stuck on why I am not able to get both Monolog and Whoops to work together.

```
...
use Whoops\Run;
use Whoops\Handler\PrettyPageHandler;

error_reporting(E_ALL);
ini_set('display_errors', 1);
//----Run Whoops #1 Location
$whoops = new Run();
$whoops->prependHandler(new PrettyPageHandler());
$whoops->register();

function exceptionHandler($e)
{ 
    //log the exception using monolog
}

function errorHandler($errno, $errstr, $errfile, $errline)
{
    //log the error using monolog
}

set_error_handler("errorHandler");
set_exception_handler('exceptionHandler');

//----Run Whoops #2 Location
```

**Comment by denis-sokolov** [comment]
Either Whoops handles the error or your custom handler, that’s how Whoops works. What you want to do is let Whoops handle the error, but add your custom handler, too.

See a few examples:
https://github.com/filp/whoops/issues/62#issuecomment-19553150
https://github.com/filp/whoops/blob/master/examples/example.php
