### ISSUE TITLE
Add support for PHPUnit 7 or 8

### ISSUE THREAD

**Issue by pascalheidmann** [filp/whoops#655]
Also maybe drop support for older PHPUnit versions (see #553)

**Comment by GrahamCampbell** [comment]
Can't drop older versions, without dropping older PHP. "support for PHPUnit 7 or 8" doesn't matter for users of this package, since it's a dev requirement.

**Comment by denis-sokolov** [comment]
Thank you for the suggestion, @pascalheidmann. As Graham has mentioned, our tests are internal and the users don’t see the difference, thus the motivation to change the tooling is very low. ¯\\_(ツ)_/¯

**Comment by SvenRtbg** [comment]
Related: #504
