### ISSUE TITLE
phpDoc comment error

### ISSUE THREAD

**Issue by bkdotcom** [filp/whoops#656]
Whoops\Exception\Frame::getFileLines()

https://github.com/filp/whoops/blob/master/src/Whoops/Exception/Frame.php#L192-L194

`$frame->getFileLines(9, 1); // array( 10 => '...', 11 => '...')`

should be

`$frame->getFileLines(9, 1); // array( 9 => '...')`

nitpick, but I scratched my head.. especially after the "(zero-indexed, remember!)" comment

**Comment by denis-sokolov** [comment]
Thank you! Fixed in c09b643.
