### ISSUE TITLE
CORS Support

### ISSUE THREAD

**Issue by liamkeily** [filp/whoops#666]
Is there a way to make whoops handler work well with Cross Origin requests? 

Currently i am unable to see error responses in chrome inspector because Cors headers do not get sent: 

`Access to XMLHttpRequest at '...' from origin '...' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

This makes debugging ajax errors more fiddly

**Comment by liamkeily** [comment]
Managed to fix by extending the handler

```
use Whoops\Handler\PrettyPageHandler;

class WhoopsCorsHandler extends PrettyPageHandler
{
    public function handle()
    {
        header('Access-Control-Allow-Origin: ' . WEB_APP_URL);
        header('Access-Control-Allow-Headers: X-Requested-With, Content-Type, Accept, Origin, Authorization');
        header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH');
        header('Access-Control-Allow-Credentials: true');

        return parent::handle();
    }
}
```

**Comment by denis-sokolov** [comment]
Unfortunately, this could mean any website on the web could retrieve details about a website you are developing on localhost. While it may be an acceptable risk for some, I don’t think we can make this judgement universally. Would you agree with that?

**Comment by liamkeily** [comment]
@denis-sokolov Yea i can see your concern there. My implementation includes WEB_APP_URL which defines which web-app has access but i'm not sure how that would work with making it part of the core. Hopefully this issue should be enough to help anyone looking to do the same.

**Comment by denis-sokolov** [comment]
Yeah, thanks a lot for bringing it up, and hopefully people can find and reuse your solution.
