### ISSUE TITLE
Reconsider use of the term "blacklist"

### ISSUE THREAD

**Issue by GrahamCampbell** [filp/whoops#667]
In `PrettyPageHandler`, would you accept a PR to change this terminology to "exclude" or "ignore"? I'd propose leaving the original in there, marked as deprecated, until such time as a major release is due.

**Comment by denis-sokolov** [comment]
This was a great opportunity to review its naming in general. Not showing a particular context value is not obvious enough to warrant such a short name. Added a better name in 5d5fe9bb3d656. Thanks for bringing this to my attention.
