### ISSUE TITLE
Support for "Solutions"?

### ISSUE THREAD

**Issue by mr-feek** [filp/whoops#670]
Inspiration:  https://github.com/facade/ignition

The ignition library for Laravel has a great concept for "solutions", a way to display a message that might potentially solve a  specific exception. Would there be interest in adding support for something similar to `whoops`?

![image](https://user-images.githubusercontent.com/5747667/87693309-aac41400-c741-11ea-92bc-24d791412437.png)

If this isn't desired in core, would there be a specific implementation you would recommend? The existing `PrettyPageHandler` seems pretty hard to override/add functionality in user-land.

**Comment by denis-sokolov** [comment]
I think it’s a nice feature, but I am not sure there is demand for it amongst Whoops users.

If you decide to work on it, consider that outputting dynamic solutions is much simpler than also handling the actions.

To avoid unnecessary rework, also consider to discuss the design of the functionality before the implementation, but at a high level something like a configuration matching errors to solutions would work well:

```php
$handler->addSolution("/Table Not Found/", "Did you forget to run your migrations?")
```

**Comment by mr-feek** [comment]
Thank you for the consideration @denis-sokolov . Would you be willing to accept a PR allowing extension of the `PrettyPageHandler`? IE, extracting some logic to methods and making the member variables `protected` instead of `private`? If so, I could easily add an area to the template to render additional info

**Comment by denis-sokolov** [comment]
Making methods and variables protected instead of private adds a considerable maintenance burden for us that I would not be comfortable taking.

But I would be happy to iterate with you to add the missing functionality to the core. Like the previously suggested `$handler->addSolution`, or, if it matches your needs better, something more free-form, like `$handler->addAdditionalHtml(function($err){ return "<div>Did you forget to run your migrations?</div>" })`.

**Comment by filips123** [comment]
Similar request (to add more useful error messages and solutions) is also #652 by @paragonie-security.

I think that it would be quite useful. Some common not framework-specific errors could be provided by default, while others should be provided via APIs by third-party packages or developers.
