### ISSUE TITLE
Add Exception code to JsonResponseHandler by default

### ISSUE THREAD

**Issue by CodeBrauer** [filp/whoops#673]
Any reason why the JsonResponseHandler is missing the Exception code?
Is there an easy way to enable it?

https://www.php.net/manual/en/exception.getcode.php

**Comment by denis-sokolov** [comment]
I suppose an oversight that nobody has ever noticed! A PR for this will be accepted. Seems to be a small change in our formatter:

https://github.com/filp/whoops/blob/fa50d9db1c0c2fae99cf988d27023effda5524a3/src/Whoops/Exception/Formatter.php#L21-L26

**Comment by CodeBrauer** [comment]
Yeah works fine.

```php
require __DIR__ . '/../vendor/autoload.php';
$run     = new Whoops\Run;
$handler = new Whoops\Handler\JsonResponseHandler();
$run->pushHandler($handler);
$run->register();
throw new Exception("Error Processing Request", 1024);
```

returns:

```json
{
  "error": {
    "type": "Exception",
    "message": "Error Processing Request",
    "code": 1024,
    "file": "/Users/gw/dev/pr-tester/whoops/examples/json.php",
    "line": 21
  }
}
```

If no code is given, it is `int:0` by default
