### ISSUE TITLE
How to generate a Whoops error page from a PHP exception?

### ISSUE THREAD

**Issue by BenMorel** [filp/whoops#679]
Hi, I'd like to integrate Whoops in my website, that's using a custom framework.

I already have an error handler that converts error to exceptions, and custom logic to determine whether to display the exception details, or a generic error page, based on whether we're in dev mode or not.

**Is there a way I can just create a Whoops error page from an exception?** So that I can decide whether to display the Whoops error page or the generic error page at that point.

Sorry if this is obvious, but I fail to get the answer from the docs!

**Comment by denis-sokolov** [comment]
This is not a common use case, but we do support it somewhat. The primary limitation is Whoops will still handle headers and output buffering.

```php
// Whenever you decide to use Whoops to display an error
$whoops = new \Whoops\Run;
$whoops->pushHandler(new \Whoops\Handler\PrettyPageHandler);
$whoops->handleException($exception);
```

**Comment by BenMorel** [comment]
Thanks a lot, @denis-sokolov!

Actually it looks like we can prevent output (headers & content), with `allowQuit(false)` and `writeToOutput(false)`:

```php
$whoops = new \Whoops\Run;
$whoops->allowQuit(false);
$whoops->writeToOutput(false);
$whoops->pushHandler(new \Whoops\Handler\PrettyPageHandler);

$html = $whoops->handleException($e);
 ```

Which perfectly fits my needs. Should this be added to the README, if anyone like me wonders the same thing?

**Comment by denis-sokolov** [comment]
Thanks for sharing a full working example! Now that we have it, yeah, good idea, I’ll add it to the readme in a bit.

**Comment by denis-sokolov** [comment]
Added in 9b57101!

**Comment by BenMorel** [comment]
Thanks! Small typo in formatting though.
