### ISSUE TITLE
Whoops needs better documentation

### ISSUE THREAD

**Issue by David263** [filp/whoops#681]
I do plain PHP programming (mostly on Windows, and mostly in websites or standalone tools), and a lot of it. I don't use any of the products you list in your Installation section. I have experimented with many error-handling mechanisms over the years. Naturally, I was interested in Whoops, which was mentioned at https://netgen.io/blog/modern-error-handling-in-php .

I've downloaded and browsed through the code, and what I see is a large number of files containing functions with very short comments to explain each, sufficient only for someone who already understands the whole thing. I could not find an overall description or user manual for this library, which I expected to be located or pointed to in the GitHub README.md file. The code file doesn't seem to include a nice PDF manual, or even a Readme.txt file.

I did look at the documentation in whoops/docs, but found these files disappointing. They mostly cover extensions. Nowhere is there a simple statement of what Whoops does, followed by a detailed description.

When I release a product, I think of the user, and provide complete and understandable documentation sufficient for the user to evaluate the software or use it. This is for me the most important part of the product (next to bug fixing), the base for presenting a user-friendly view to the future audience for the product.

Standard PHP error handling is neither pretty nor complete nor easy to extend to reporting syntax errors in the software tools that I create. So I was interested in Whoops. But all I see here is a collection of interestingly-named functions, with no overall coordination or description of operation. I can't even find any ready-to-run understandable usage examples (https://github.com/filp/whoops/blob/master/examples/example.php is the most unreadable code I've seen, using lots of "advanced" PHP features that are hard to understand, such as namespaces, and using Whoops functions without explaining what they do or why they are useful).

Unfortunately, I don't have the time to read and think about all this code to determine exactly what it is doing. So I won't be using Whoops. Just some feedback; hope it is useful.

**Comment by denis-sokolov** [comment]
Thanks for sharing your experience! This might help us proceed in the future. Sorry to hear you could not benefit from Whoops.

It is true that we have certain expectations when developing products and in this case it seems that your expectations are not matched by the audience we target. In particular, installing packages without Composer is, indeed, not supported. To a similar vein, for the main use case of showing a nicer error page, the entire contents of the package should be considered opaque implementation details and the three lines of code in the main documentation is all that should be considered the API. I wish you find a tool that helps you with the errors while matching your application setup better!
