### ISSUE TITLE
Whoops is not working with Xdebug 3

### ISSUE THREAD

**Issue by PSchwalkowski** [filp/whoops#682]
Whoops seems to not work well with Xdebug3

Call to undefined function Whoops\Exception\xdebug_is_enabled()

![image (1)](https://user-images.githubusercontent.com/22113470/101751654-cce37780-3ad0-11eb-83de-fec82b51fa71.png)

I'm using PHP 7.4.9 and this php.ini config
```
xdebug.mode = default
xdebug.start_with_request = trigger
xdebug.output_dir = "F:\Projects\xampp\tmp"

xdebug.remote_handler = "dbgp"
xdebug.log = "F:\Projects\xampp\tmp\xdebug-php-749.txt"
xdebug.discover_client_host = false
;36000 = 10h
xdebug.remote_cookie_expire_time = 36000
xdebug.max_nesting_level = 400
```

With Xdebug 2.9 everything is just fine.

**Comment by staabm** [comment]
I think we should feature detect this with `function_exists(..)`

**Comment by SvenRtbg** [comment]
At least the migration guide of Xdebug states that `xdebug_is_enabled()` is removed in v3 and was never intended to be used in v2 anyways. 

https://xdebug.org/docs/upgrade_guide#Changes-to-Functions

**Comment by soutorafaelbr** [comment]
https://github.com/filp/whoops/commit/dc30a4cb68b45a5fb65e190cf0a6b58d3d3ef096

**Comment by denis-sokolov** [comment]
Thanks, @soutorafaelbr, for noticing that it’s already added in #677.  @PSchwalkowski, try Whoops 2.9.1 for the workaround!
