### ISSUE TITLE
在调试模式下，whoops无法使用左边按钮，也就是js是无效的

### ISSUE THREAD

**Issue by jinmarcus** [filp/whoops#683]
在调试模式下，whoops无法使用左边按钮，也就是js是无效的

![20201219084306](https://user-images.githubusercontent.com/17996289/102676055-c773e480-41d6-11eb-8a73-451a4fb2e872.png)

https://s3.ax1x.com/2020/12/19/rtss56.png

**Comment by GrahamCampbell** [comment]
Please upgrade to the latest version of whoops.

**Comment by GrahamCampbell** [comment]
See https://github.com/filp/whoops/issues/588.
