### ISSUE TITLE
Decide which exit code to send

### ISSUE THREAD

**Issue by lode** [filp/whoops#688]
It would be nice if we could decide which exit code gets send to CLI, in the same way we can do that with HTTP response codes. Right now `$this->system->stopExecution(1);` is being called which hard codes this.

I'm willing to setup a PR for this if this is a desired direction.

**Comment by denis-sokolov** [comment]
Sounds like a perfectly valid option to add! I think it would be close to [allowQuit option](https://github.com/filp/whoops/blob/6ecda5217bf048088b891f7403b262906be5a957/src/Whoops/Run.php#L212) we have on Run.
