### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by Crell** [filp/whoops#697]
This package is licensed MIT.

However, the README includes this statement:

```
This software includes Prettify, licensed under Apache License 2.0. It is bundled only as a performance optimization.
```

If that's the case, then no, this package is not MIT licensed.  It's Apache 2 licensed, and thus is incompatible with any GPLv2-based application.

I haven't gone looking for the Prettify code, but the current licensing information on this project is incorrect, and thus is a trap for anyone using the GPL.  Please either change the license to Apache 2 to be accurate, or remove the Apache 2 code so that it can be properly MIT.  (The status quo is, I believe, technically a license violation.)

**Comment by AmraniCh** [comment]
I think they mean in the README that the [Prettify ](https://github.com/googlearchive/code-prettify)is licensed under Apache License and not whoops, the whoops repo contains an MIT license file and thus is LICENSED under the MIT license, but I see it better to more clarify things in the README.

**Comment by Crell** [comment]
1) If this package includes the code from Prettify copy and pasted in, then at least that file is still Apache2, not MIT. (I don't think the whole library technically is.)
2) If this package were to instead depend on Prettify as a dependency (it currently does not), that would still be a problem for anyone using this package as they'd be pulling in Apache2 code along with this code.

Unless there is actually no Prettify involved anywhere and the README statement is just vestigial, this library is incompatible with GPLv2.

**Comment by denis-sokolov** [comment]
Thank you, @Crell, for noticing this!

Switched to prism.js in 2.14.0!
