### ISSUE TITLE
Really Great repo. Any plans for a few more?

### ISSUE THREAD

**Issue by drakakisgeo** [filp/whoops#698]
Hi Matt, I was really glad to find this repo. Any plans to include any of those packages "illuminate/testing" , "illuminate/validation", "illuminate/mail" in the future ? Struggling to find the way to do it in an old Slim API.

In the meantime if I figure it out those myself, I will definitely make a PR, since this is really really useful for legacy apps.

Again, thanks for your openness .

**Comment by staabm** [comment]
>  Any plans to include any of those packages

why? for which benefit?

**Comment by drakakisgeo** [comment]
Really sorry.
