### ISSUE TITLE
Limit the number of frames shown to prevent browser crashes

### ISSUE THREAD

**Issue by calvinalkan** [filp/whoops#700]
Hello,

I have used whoops for some months in a project where I built a custom error handler that integrates nicely with whoops. 

Recently I noticed that when an exception gets thrown after a relativly "large" stack trace (maybe 100 frames in whoops ) the error page initially rendors correctly bit as soon as I click one different frame in the side panel my entire browser freezes and then crashes. Tried in chrome and firefox on two pcs. 

Is this to be expected? I could not find anything in the docs regarding setting a frame limit. 

Thank you, 

Calvin

**Comment by staabm** [comment]
Could you create a test case which reproduces the problem?

**Comment by denis-sokolov** [comment]
I suppose a setting to show only the top x frames could make sense to work around any limitations in the browser. A PR is welcome.

**Comment by denis-sokolov** [comment]
I’ve added this to the [list of possible features to add](https://github.com/filp/whoops/wiki/Possible-features-to-add).
