### ISSUE TITLE
Catch php.ini warnings

### ISSUE THREAD

**Issue by futzlarson** [filp/whoops#708]
I should first mention this is not an issue with Whoops itself, more of a question about what is possible. But I just learned that Laravel is using Whoops, so nice job!

Recently I ran into an issue when upgrading PHP from 7.2 to 7.3 and that using the default `php.ini` (which was surprising). More details [here](https://laracasts.com/discuss/channels/laravel/catch-whoops). My question is about catching this type of issue, to which a top responder said:

> the error occurs before calling index.php and booting the framework, so, no.

So I figured I would ask someone with much deeper experience of error-handling in PHP. Any ideas for how to catch this sort of error/warning? Here's the error:

`2021/09/21 10:09:03 [error] 8524#8524: *127979 FastCGI sent in stderr: "PHP message: PHP Warning:  POST Content-Length of 21212749 bytes exceeds the limit of 8388608 bytes in Unknown on line 0" while reading response header from upstream, (rest removed)`

I could monitor the `/var/log/nginx/` log file with a scheduled task, but I'm wondering if you know of a better solution? A bit OCD I know. I just like being aware of all errors happening, and I hadn't considered this type before.

**Comment by denis-sokolov** [comment]
Alas, I don’t have any insight that can help you further. And seeing the lack of responses from other contributors, the hope is dwindling. :-(

**Comment by futzlarson** [comment]
All good. I wrote a scheduled command to check the previous day's logs.
