### ISSUE TITLE
Getting PHP Parse error when running the package in PHP 5.6.40 version

### ISSUE THREAD

**Issue by AmraniCh** [filp/whoops#710]
Whoops is supposed to work without any problems in PHP ^5.5.9 versions as indicated in the `composer.json` file, I've run Whoops in a PHP 5.6.40 CLI and I've got this error.

<pre>PHP Parse error:  syntax error, unexpected &apos;:&apos;, expecting &apos;;&apos; or &apos;{&apos; in /home/amranich/Desktop/ajax-dispatcher/vendor/filp/whoops/src/Whoops/Exception/FrameCollection.php on line 181
</pre>

If you planning to not support PHP 5 anymore then the `composer.json` must be updated and I think a lot of things must be changed too, if not I can create a PR to remove the return type declaration that causes this error.

**Comment by SvenRtbg** [comment]
Your error message does not seem to point to something from the Whoops project.

**Comment by AmraniCh** [comment]
@SvenRtbg Thanks for your notice, I've updated the error.

**Comment by SvenRtbg** [comment]
Yes, now it makes sense, and it looks like the offending code was added just two weeks ago. See #706 .

**Comment by SvenRtbg** [comment]
Seems like there is at least a loophole in the test infrastructure now. TravisCI.org stopped working months ago, some transition has to be made to TravisCI.com - and that's where PHP5 relates tests would be running. The Github checks integration is only validatingf PHP 7.

**Comment by AmraniCh** [comment]
@SvenRtbg Emm, so the PHP 5 compatibility is already broken now and I think the return types should be removed.

**Comment by denis-sokolov** [comment]
Thank you folks for noticing and investigating! Now fixed in 9814ccd, 2.14.4.
