### ISSUE TITLE
Adding an additional member variable and getter to PrettyPageHandler

### ISSUE THREAD

**Issue by Baylie21** [filp/whoops#713]
I would like to propose an addition to the PrettyPageHandler. I have been testing serializing and unserializing errors produced by our codebase in order to easily see what's going on when an issue occurs during one of our cron jobs.

the main flow of this involves serializing and unserializing the tables and then feeding them back into a prettypagehandler and throwing the exception. Right now, i am able to access the user added data tables, but not the standard base tables, as they are created in the handle() method on 183 in PrettyPageHandler.php. 

I would like to propose adding a member variable, '$allTables' which would be set on ln 285. 

`$this->all_tables = $vars["tables"] = array_merge($extraTables, $vars["tables"]);`

by then adding a getAllTables() method, one could easily grab all of the tables to recreate the page

![image](https://user-images.githubusercontent.com/32575408/139493540-73c8a5ed-7e76-4e84-8d88-e9a04b1301ca.png)

**Comment by denis-sokolov** [comment]
I can see benefit in this and would possibly merge a PR that does this. But we’d need a good example in the documentation to the explain how to use this to unserialize previous errors.
