### ISSUE TITLE
Is it able to run with swoole? 

### ISSUE THREAD

**Issue by topyao** [filp/whoops#721]
I tried but the function returned an empty string. 

```php
$whoops->handleException($e);
```

**Comment by denis-sokolov** [comment]
I’m sorry, this does not seem to be a clearly described issue. Given your description, it is tricky to figure out what went wrong. Perhaps you should first try other avenues of action, such as investigate the problem further, ask for help on support forums. You could also try to come up with a simpler way to reproduce your problem on a website like jsfiddle.net. If you have new findings, by all means, feel free to add them here and the issue might be reopened.
