### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by KaeruCT** [filp/whoops#73]
Hi, I'm getting an out of memory error sometimes (but not always).
PHP Version: `PHP 5.3.10-1ubuntu3.6 with Suhosin-Patch (cli) (built: Mar 11 2013 14:31:48) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
    with Xdebug v2.2.1, Copyright (c) 2002-2012, by Derick Rethans`

Apache version: `Server version: Apache/2.2.22 (Ubuntu)`
Ubuntu version: `Ubuntu 12.04.2 LTS`

The following is from the apache error log:
`[Fri Jul 05 11:46:58 2013] [error] [client 127.0.0.1]
PHP Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 950988674 bytes) in
/var/www/test/vendor/filp/whoops/src/Whoops/Resources/pretty-template.php
on line 129, referer: http://localhost/`

The referenced line contains the following:
`<td><?php echo $e(print_r($value, true)) ?></td>`

I think it might be choking up on recursive structure, but I don't really know if this could be considered a PHP bug instead of a bug with whoops.

**Comment by jissereitsma** [comment]
I have bumped into the same issue: Replacing `print_r` with `var_dump` in `Whoops/Util/TemplateHelper.php` fixes this. So it seems that `print_r` should handle recursion internally, but it doesn't. I checked and on PHP fora this is familiar difference the two calls, where `var_dump` is actually designed to bypass this issue of `print_r`. I have added a simple PR for this now: https://github.com/filp/whoops/pull/545
