### ISSUE TITLE
Ignore specific exceptions

### ISSUE THREAD

**Issue by JoyceBabu** [filp/whoops#763]
How can I make Whoops ignore specific exceptions?

For example, my app throws an HttpException, which will be handled by the global error handler to display the appropriate error page. I have Whoops enabled only in development environment. This is causing Whoops handler to execute instead of the global handler.

How can I make Whoops ignore only HttpExceptions?

**Comment by denis-sokolov** [comment]
That’s the thing with global scope: it’s shared. There can be only one global error handler. If you request Whoops PrettyPageHandler to handle the error, it will do that. Whoops does not support being asked to handle the error and then not handling the error.

I can suggest two options: add your handler to be called from Whoops or call Whoops PrettyPageHandler from your handler. For former, you can use `$whoops->pushHandler(function($exception) {});` and return `\Whoops\Handler\Handler::DONE` to stop. For latter, you can instantiate \Whoops\Handler\PrettyPageHandler yourself and call its `->handle`.

**Comment by JoyceBabu** [comment]
I did end up calling my custom handler from Whoops. 

But I think the second option is even better. Thank you.
